### ISSUE TITLE
'compliancy' is a valid word

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#1062]
https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt#L3043

https://www.merriam-webster.com/thesaurus/compliancy

**Comment by peternewman** [comment]
I'm not sure this needs an issue @luzpaz, if it's a valid word, it just needs fixing.

I'm beginning to wonder if we should validate the alleged typos in the Codespell dictionary against a word list of valid spellings during CI, as things like this seem to keep creeping in when people source typos from existing codebases (where an infrequently used but valid word may be a typo for another, also valid, word).

**Comment by luzpaz** [comment]
> I'm beginning to wonder if we should validate the alleged typos in the Codespell dictionary against a word list of valid spellings during CI, as things like this seem to keep creeping in when people source typos from existing codebases

Yes, you're on to something here.
