### ISSUE TITLE
mut is a keyword in rust

### ISSUE THREAD

**Issue by nils-van-zuijlen** [codespell-project/codespell#1109]
I have an app which is partly written in rust, but the keyword `mut` (used to tell that a variable is not constant) is recognised as `mut ==> must, mutt, moot`.

Are there any way to disable it on `.rs` files ?

**Comment by peternewman** [comment]
@nils-van-zuijlen using --ignore-words should do the job, or the exclude list:
https://github.com/codespell-project/codespell/blob/master/codespell_lib/_codespell.py#L248-L250
