### ISSUE TITLE
Switch Codecov to the status API rather than comments

### ISSUE THREAD

**Issue by peternewman** [codespell-project/codespell#1136]
https://docs.codecov.io/docs/commit-status

To avoid comment spam, and optionally make equal/improving coverage a merge requirement.

**Comment by larsoner** [comment]
Feel free to make a PR to add the YAML file

**Comment by peternewman** [comment]
@larsoner can you see what's inside https://codecov.io/account/gh/codespell-project/yaml ? I think it might be overriding what I'm trying to do in #1166 .

Or it might be the request to install the app I've just issued was needed: https://github.com/apps/codecov

**Comment by larsoner** [comment]
I just accepted the app integration request

**Comment by larsoner** [comment]
For some reason https://codecov.io/account/gh/codespell-project/yaml gave me a 401 until I enabled private repo scope for `codespell-project`, now it shows up but looks pretty blank. Maybe now it will work?

**Comment by larsoner** [comment]
I also wonder if it's possible that `codecov` uses the `master` config at all times, meaning you can't change it via PR but only via direct push. It would be weird but it could be what's happening

**Comment by larsoner** [comment]
I also just modified

https://codecov.io/account/gh/codespell-project/yaml

To have this as the team YAML:
```
codecov:
  bot: larsoner
```
No idea if it will help, but seemed worth a shot

**Comment by peternewman** [comment]
Thanks @larsoner , I think that can be removed again, as I was beginning to suspect it is now working as a commit status, it just needs a commit which actually has some coverage impact to do things. See for example:
https://github.com/codespell-project/codespell/pull/1163

The default YAML seems fairly sane if I just turn off the comment option:
https://docs.codecov.io/docs/codecov-yaml#section-default-yaml

Then it's really just a case of if we actually want to tweak the number and type of commit statuses it returns, e.g. differentiating test from app like in some of their examples.

**Comment by larsoner** [comment]
I don't think we need to separate, this is not a huge (Python) project.

Okay to merge from your end?

**Comment by peternewman** [comment]
Yeah go for it, I've just had both a comment and a status despite not changing anything, but lets get it in and then see if it really works with some live PRs.
