### ISSUE TITLE
The referer misspell

### ISSUE THREAD

**Issue by gpotter2** [codespell-project/codespell#1143]
Hi! Thanks for this great project.

I know "referer" technically is a misspell, however, it's a misspell that got used within the HTTP 1.0 RFC and is still to this day the name of a well-used HTTP field: https://en.wikipedia.org/wiki/HTTP_referer

I'm guessing it should be on my responsibility to add it to the ignore file, but I thought I'd first bring this here to ask whether you wanted to allow the misspell. I don't know how common it is

**Comment by peternewman** [comment]
@gpotter2 just open a Pull Request to update the entry to say it's disabled, like movei:
`movei->movie, disabled due to assembly code`
