### ISSUE TITLE
Feature: update dictionary.txt without waiting for the next version

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#116]
An idea to add functionality that checks for the latest dictionary.txt file on GitHub and downloads it if needed.

**Comment by luzpaz** [comment]
Is it really just being as simple as pullling `https://github.com/lucasdemarchi/codespell/blob/master/codespell_lib/data/dictionary.txt` down to `/usr/lib/python3.6/site-packages/codespell_lib/data/dictionary.txt` ?

**Comment by lucasdemarchi** [comment]
if the format didn't change in a way that it depends on the feature from codespell itself, yes.

**Comment by luzpaz** [comment]
> if the format didn't change in a way that it depends on the feature from codespell itself, yes.

Can codespell test for that ?

**Comment by luzpaz** [comment]
> if the format didn't change in a way that it depends on the feature from codespell itself, yes.

@lucasdemarchi what is the context in which something like this can happen?

**Comment by luzpaz** [comment]
@thdot do you care to weigh in on this thread ?

**Comment by thdot** [comment]
I would like the feature.

I've thought about a implementation of this and here is my proposal:
We introduce a new catalog JSON file in the data directory which describes the _format-version_ as well as all supplied dictionaries (currently we have only one, but I think we could have easily more dictionaries for different languages in the future), The catalog could look like 
```json
{
  "format-version": 1.0,
  "dictionaries": ["english.txt", "german.txt"]
}
```
codespell would then first download the catalog file, check if the format-version is supported, and then download the dictionary file(s). Thereby we can detect future format changes (for example to allow comments in the dictionary) and support the download of multiple files.

What do you think? @lucasdemarchi @larsoner @luzpaz

**Comment by luzpaz** [comment]
Interesting. 
Though how does this address revisions to the dictionary in between major or minor releases of codespell ?

> if the format didn't change in a way that it depends on the feature from codespell itself, yes.

Your idea of a _format-version_ would take care of this

the multiple dictionary is also a cool idea...but each dictionary would need an admin to be in charge of it's typos, what is valid and what isn't.

**Comment by luzpaz** [comment]
I've gotten some feedback from users who have used codespell after I've demonstrated it to them, and they don't seem to get the same results when running it. This is because the `dictionary.txt` file gets updated for them only during new releases. This feature request would ensure that these end-users can stay current with upstream `dictionary.txt`

**Comment by larsoner** [comment]
I think this is out of scope, use `wget` or something else to pull it from GitHub

**Comment by luzpaz** [comment]
If it's out of scope then I propose mentioning something in the docs for folks who want a workaround if we are not embedding this in to codespell.

Like a bash script that figures out where:  `codespell/codespell_lib/data/dictionary.txt` is and then use `curl` or `wget` to grab `https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt`

**Comment by larsoner** [comment]
I don't see a need to replace the builtin one, just do:
```
wget https://raw.githubusercontent.com/codespell-project/codespell/master/codespell_lib/data/dictionary.txt
codespell -D dictionary.txt ...
```

**Comment by luzpaz** [comment]
https://github.com/codespell-project/codespell/pull/847
