### ISSUE TITLE
Wrong string detection with version 1.15.0 and 1.16.0

### ISSUE THREAD

**Issue by sbrunner** [codespell-project/codespell#1251]
With a js file like that
```js
a = 'Missing files';
```
I get the error:
```
test.js:1: files'  ==> file's
```

**Comment by peternewman** [comment]
I think that's expected, this system doesn't currently inspect the code, so doesn't realise you're quoting a string and hence assumes you've got an errant apostrophe.

**Comment by sbrunner** [comment]
Then why it was working in version 1.14.0?
Is it possible to ignore this kind of errors?

**Comment by peternewman** [comment]
> Then why it was working in version 1.14.0?

Because that correction was only added in the change between the two:
https://github.com/codespell-project/codespell/compare/v1.14.0...v1.16.0#diff-3bddc99f1f6dffc98ea11be5a5a31ae9R8677

> Is it possible to ignore this kind of errors?

Yes, you can whitelist either specific lines or corrections, see the man pages/help for Codespell.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by larsoner** [comment]
Sounds like this is resolved enough, closing

**Comment by sbrunner** [comment]
It's not fixed I just found a workaround...

**Comment by peternewman** [comment]
> It's not fixed I just found a workaround...

I think a proper fix for this would need a full code parser for example you can't just check if there is a preceding single quote due to scenarios like this where it should flag the issue:

`a = 'Foo's files' live here';`
