### ISSUE TITLE
make check-dictionary should check for incorrect delimiters

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#1263]
Currently `make check-dictionary` doesn't report a problem when entries are incorrectly formatted e.g.
`typo>correction`  
`typo=>correction`  

The code in TravisCI should be ported to check-dictionary.

**Comment by peternewman** [comment]
So those other checks are done by running `pytest codespell_lib`, but you probably just want to run the pytests in `codespell/codespell_lib/tests/test_dictionary.py` and you might want to check pytest exists first, although I guess this is only run by "developers" not users.
