### ISSUE TITLE
TODO file is obsolete should be removed or edited to indicate repo issue queue is new location

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#1306]
File: [TODO](https://github.com/codespell-project/codespell/blob/master/TODO)

I propose removing but if that's not consensus... then just modifying the file to simply say: 
`TODOs migrated to https://github.com/codespell-project/codespell/issues`

Thoughts ?

**Comment by larsoner** [comment]
Agreed

**Comment by luzpaz** [comment]
@larsoner to remove or to modify ?

**Comment by larsoner** [comment]
I would just remove it
