### ISSUE TITLE
Ignoring words that give a problem (whitelisting)

### ISSUE THREAD

**Issue by albert-github** [codespell-project/codespell#1310]
I have a problem whitelisting some words (in version 1.16). Say I have the file
```
/*! \brief Include relation
 */
class IInclude
{
};
/*! \brief Include relation
 */
class aaccession
{
};
```
In that case I get the warnings when I just use `codespell`:
```
aa.h:3: IInclude  ==> include
aa.h:8: aaccession  ==> accession
```
but as we know in this case both are valid words I want to ignore them, so I run `codespell -L IInclude,aaccession` but I still get the message:
```
aa.h:3: IInclude  ==> include
```

How to do this properly?

Edit:
Also creating a file `whitelist.txt` with:
```
IInclude->Include
```
and running `codespell   -D whitelist.txt -D - -L IInclude,aaccession` does not bring a solution, still the same message with even a lowercase `i` for the `include`

**Comment by peternewman** [comment]
Please see the help (my bold):
`Comma separated list of words to be ignored by codespell. Words are **case sensitive based on how 
they are written in the dictionary file**`

So you want `-L iinclude,aacession`:
https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt#L10511

You can also whitelist the entire line with another flag.

**Comment by albert-github** [comment]
Yes this works.

The **case sensitive based on how they are written in the dictionary file** is clear, but as the message said:
```
aa.h:3: IInclude  ==> include
```
the first impression is that the word to be excluded is 'IIncllude' and not 'iinclude'.

**Comment by peternewman** [comment]
> the first impression is that the word to be excluded is 'IIncllude' and not 'iinclude'.

I think this is the balance between making it clear for the general case (i.e. when you see a typo finding the context for it in your code), versus the specific case of white-listing (where you need it to match the case in the dictionary).

**Comment by albert-github** [comment]
Isn't it the case that the context can be found with `-C 0`?

**Comment by peternewman** [comment]
> Isn't it the case that the context can be found with `-C 0`?

Yeah I guess, but at a glance you might prefer the unadulterated one. Possibly one for @larsoner and others.
