### ISSUE TITLE
Possibly add Travis typos

### ISSUE THREAD

**Issue by peternewman** [codespell-project/codespell#1312]
Some may be Travis specific, but a lot are generic:
https://github.com/travis-ci/travis-yml/blob/master/var/keys.dict

Any ideas on how copyright applies to this? They're MIT licenced.
https://github.com/travis-ci/travis-yml/blob/master/LICENSE

**Comment by larsoner** [comment]
My understanding is that you can use MIT code in GPL projects (MIT is compatible with use in GPL) but not the other way around. So as long as we add a note somewhere that the entries were adapted it seems fine

**Comment by DimitriPapadopoulos** [comment]
The dictionaries are released under the [Creative Commons Attribution-Share-Alike License 3.0](https://creativecommons.org/licenses/by-sa/3.0/), aren't they?

**Comment by skangas** [comment]
> The dictionaries are released under the [Creative Commons Attribution-Share-Alike License 3.0](https://creativecommons.org/licenses/by-sa/3.0/), aren't they?

Yup. The good news is that the MIT license allows redistributing under any license you like, including a proprietary one, as long as you include the copyright statement from the original work.
