### ISSUE TITLE
RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode with Python 3.8

### ISSUE THREAD

**Issue by ahal** [codespell-project/codespell#1331]
Running latest codespell under Python 3.8 results in the following warning:
```
.pyenv/versions/3.8.0/lib/python3.8/codecs.py:905: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  file = builtins.open(filename, mode, buffering)
```

This was introduced in Python 3.8 here:
https://bugs.python.org/issue32236

**Comment by larsoner** [comment]
This was fixed by #1401

**Comment by postlund** [comment]
I encountered this warning as well, has any release to pypi been made with the fix yet? Or any plans to do so?

**Comment by larsoner** [comment]
Yes we will update at some point, no date set but maybe in a month or so after people have tried the new dict system

**Comment by peternewman** [comment]
@larsoner can we do this soon please as it generates unnecessary annotations too:
https://github.com/codespell-project/codespell-problem-matcher/actions/runs/110618056

**Comment by larsoner** [comment]
Done

https://pypi.org/project/codespell/1.17.0/
