### ISSUE TITLE
Could you please consider adding "reomve" as a version of "remove"?

### ISSUE THREAD

**Issue by Dmitry-Me** [codespell-project/codespell#1385]
Looks like the following correction would be useful:

reomve -> remove

and it looks like "reomve" is not an existing word that would have any meaning.

**Comment by peternewman** [comment]
Feel free to just edit the file in future and it will generate a Pull Request for you @Dmitry-Me .

**Comment by peternewman** [comment]
Hi @Dmitry-Me , @luzpaz fixed this for you and it's just gone in as part of  #1432
