### ISSUE TITLE
'ue' should be corrected to 'use' instead of 'due'

### ISSUE THREAD

**Issue by waldyrious** [codespell-project/codespell#1413]
I'm not sure this is fixable, since the word is so small it may throw off most reasonable metrics to pick one correction or the other. In particular, I assume that adding a character at the start or end of a misspelled sequence (which does not modify the sequence) may be scored higher than adding a character in the middle.

However, if no such heuristic is in place, then I'd suggest that in cases like this the most common word be scored higher ("use" is the [244th](https://www.wolframalpha.com/input/?i=word+frequency+of+use) most common English word, while "due" is [the 1331st](https://www.wolframalpha.com/input/?i=word+frequency+of+due)).

**Comment by larsoner** [comment]
Done in #1414
