### ISSUE TITLE
Ignore "\n"

### ISSUE THREAD

**Issue by akaszynski** [codespell-project/codespell#1421]
`codespell` is great, and we're using it to check our python source files in `pyvista`, but we're having issues with our jupyter notebooks.  For example: "\nTo" is recognized as a spelling error.

Is there any way to have `codespell` recognize and ignore line breaks?

**Comment by larsoner** [comment]
Closing as dup of #233. No way to do it currently but it would be great if someone volunteered to implement it!

**Comment by akaszynski** [comment]
Didn't see that, thanks!
