### ISSUE TITLE
Incorrect suggestion: convexes -> convex

### ISSUE THREAD

**Issue by JustAndreww** [codespell-project/codespell#1426]
convexes is a plural form and it's totally correct
can reproduce with the latest master

https://en.wiktionary.org/wiki/convex
https://word.labstack.com/convex/plural

**Comment by peternewman** [comment]
Feel free to just edit the file and it will generate a Pull Request for you @JustAndreww .

**Comment by skangas** [comment]
This is no longer in `dictionary.txt`, so I think this issue could be closed.

**Comment by DimitriPapadopoulos** [comment]
Fixed by #1624.
