### ISSUE TITLE
make check-dictionary error

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#1489]
```
make check-dictionary
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=codespell_lib --cov-report=
  inifile: /home/foo/Projects/codespell/setup.cfg
  rootdir: /home/foo/Projects/codespell

make: *** [Makefile:19: check-dictionaries] Error 4
```

codespell v1.17.0.dev0

**Comment by larsoner** [comment]
You need `pytest-cov` installed

**Comment by luzpaz** [comment]
is there a way to make it a dependency of codespell that lets the user know they need to install it ?

**Comment by luzpaz** [comment]
`aspell` as well ?

**Comment by luzpaz** [comment]
Installing `python-pytest-cov` worked on Manjaro

**Comment by larsoner** [comment]
> is there a way to make it a dependency of codespell that lets the user know they need to install it ?

We don't want to make it a main dependency of `codespell` because you don't need it to use codespell, you need it to contribute to codespell (test/develop for it). There might be some way to document this in `setup.py` but I'm not sure. I'd rather just document it in the README
