### ISSUE TITLE
Add a GitHub Action for codespell

### ISSUE THREAD

**Issue by peternewman** [codespell-project/codespell#1499]
Using this seems easiest:
https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

This looks like quite a good example to base it on:
https://github.com/TrueBrain/actions-flake8

There are a couple of Codespell actions already:
https://github.com/marketplace?type=actions&query=codespell

Both by @plettich .

One just uses the dictionary, and so presumably would need an update for out multi-dictionary, won't have the same options etc (as well as only creating review comments):
https://github.com/marketplace/actions/codespell-action

The other one uses Review Dog, which seems like an unnecessary overhead now the problem matchers exist:
https://github.com/marketplace/actions/run-codespell-with-reviewdog

**Comment by peternewman** [comment]
For just how awesome this is, see here:
https://github.com/codespell-project/codespell/pull/1502/files

**Comment by larsoner** [comment]
Seems useful to me

**Comment by peternewman** [comment]
First draft:
https://github.com/peternewman/actions-codespell/actions/runs/102795540

We'll need to move this into the project at some point too. I'm sure it needs a bit of tidying up...

**Comment by peternewman** [comment]
It's also currently catching the line buffering error from #1331 .

**Comment by plettich** [comment]
Hi,
the actions in the marketplace were a first attempt from me on GitHub Actions. We use the ReviewDog variant in our project. I would be happy to turn the development over to a more appropriate organization :-)

**Comment by peternewman** [comment]
Heh thanks @plettich . Have you got a ReviewDog one you could link to?

Or alternatively here's the first draft of annotations, which I assume is probably better:
https://github.com/peternewman/actions-codespell/pull/1/files

**Comment by plettich** [comment]
The code can be found here: https://github.com/plettich/action-codespell
It looks like this: https://github.com/plettich/privacyidea/pull/17/files

**Comment by peternewman** [comment]
> It looks like this: https://github.com/plettich/privacyidea/pull/17/files

Thanks @plettich . Looks like ReviewDog only adds a little bit of noise, but I suspect doing it directly would be easiest.

**Comment by peternewman** [comment]
We should also get this repo moved to the codespell-project org at some point @larsoner . I think I just temporarily need the right to create repositories in the org to be able to migrate it.

**Comment by cclauss** [comment]
https://github.com/okken/cards/pull/43 —> https://youtu.be/2OD8E9ziSYQ

**Comment by peternewman** [comment]
> [okken/cards#43](https://github.com/okken/cards/pull/43) —> https://youtu.be/2OD8E9ziSYQ

That's neat @cclauss .

Personally I think the annotation is the real winner here, although I think we could also ship an action which just adds the matchers (and use that in our full action), so you'd then get the best of both worlds.

**Comment by plettich** [comment]
> > It looks like this: https://github.com/plettich/privacyidea/pull/17/files
> 
> Thanks @plettich . Looks like ReviewDog only adds a little bit of noise, but I suspect doing it directly would be easiest.

actually it also limits the output only to the code touched in the PR, which can be nice if You have a large Project and don't want to struggle with excluding files and samples.

**Comment by peternewman** [comment]
> I would be happy to turn the development over to a more appropriate organization :-)

@plettich now our action is released and in use by people, do you fancy signposting it from your action?

It might also avoid you needing to deal with issues like this :wink: :
https://github.com/plettich/python_codespell_action/issues/7

**Comment by skangas** [comment]
Could this issue be closed?

**Comment by cclauss** [comment]
Yes.  https://github.com/codespell-project/actions-codespell
