### ISSUE TITLE
New wordings suggestion

### ISSUE THREAD

**Issue by vikivivi** [codespell-project/codespell#1506]
overwride->overwrite
constitue->constitute
constitues->constitutes
troublshooting->troubleshooting

**Comment by peternewman** [comment]
Hi @vikivivi ,

The easiest way to add these is just to do a Pull Request yourself. You can do it all from the web interface and GitHub will guide you through it:
https://github.com/codespell-project/codespell/edit/master/codespell_lib/data/dictionary.txt

**Comment by peternewman** [comment]
Thanks @vikivivi .
