### ISSUE TITLE
dictionary_rare missing

### ISSUE THREAD

**Issue by dtrodrigues** [codespell-project/codespell#1516]
`codespell_lib/data/dictionary_rare.txt` is missing in the 1.17.0 PyPI source package causing a crash when all builtin dictionaries are used.

**Comment by larsoner** [comment]
Ouch you're right! Just pushed a 1.17.1 that hopefully fixes it. Let me know...

**Comment by dtrodrigues** [comment]
Thanks for the quick fix! Looks good now.
