### ISSUE TITLE
Filenames of empty files are not checked

### ISSUE THREAD

**Issue by per1234** [codespell-project/codespell#1532]
If a file has no content, `codespell --check-filenames` doesn't detect misspelled words in the filename:
```
$ codespell --version
1.18.dev0
$ touch abandonned
$ codespell --check-filenames
$ echo "foo" > abandonned
$ codespell --check-filenames
./abandonned: abandonned ==> abandoned
```

**Comment by peternewman** [comment]
Good find. I think this is due to `os.path.getsize` here:
https://github.com/codespell-project/codespell/blob/3ed982c/codespell_lib/_codespell.py#L722
