### ISSUE TITLE
Add codespell  project configuration file

### ISSUE THREAD

**Issue by tomasbw** [codespell-project/codespell#1585]
I would appreciate if we can have project specific .codespell configuration file so I can run codespell w/o any arguments,. 
This is useful if the same codespell run is performed by CI and also from a developer console, the most annoying is the skip list which can be pretty long.  It's possible to create a wrapper script which is called from a console and from CI, but a standard .codespell config file would be more natural.

**Comment by peternewman** [comment]
Yes, :100: I was going to raise an issue about the same thing. Especially having found the equivalent flake8 behaviour.

This would also make the action ( https://github.com/codespell-project/actions-codespell/ ) trivial to implement too.

Someone had some similar behaviour with precommit and were essentially storing their config in their, and running that as an action, but having it built in means it works for everyone!
