### ISSUE TITLE
Add trasform?

### ISSUE THREAD

**Issue by tbm** [codespell-project/codespell#1586]
How about adding "tranform"?

```
trasform->transform
trasformation->transformation
trasformations->transformations
```

Should I open a PR?

**Comment by peternewman** [comment]
Yeah a PR is the easiest way.

You can do so on the GitHub website just as easily as creating an issue, just follow this link:
https://github.com/codespell-project/codespell/edit/master/codespell_lib/data/dictionary.txt

**Comment by vikivivi** [comment]
Appreciated that the PR also included these.

```text
trasform->transform
trasforms->transforms
trasformed->transformed
trasforming->transforming
trasformable->transformable
trasformation->transformation
trasformations->transformations
trasformative->transformative
trasformer->transformer
trasformers->transformers
```

**Comment by tbm** [comment]
> Appreciated that the PR also included these.

Good point
