### ISSUE TITLE
endcode is used intentionally

### ISSUE THREAD

**Issue by sebweb3r** [codespell-project/codespell#1612]
In the dictionary.txt endcode is changed to encode.
However, endcode is often used intentionally: https://grep.app/search?q=endcode

I propose to kick it out of the dictionary or to prevent auto-fix.

**Comment by peternewman** [comment]
Looks like it should be moved to the code dictionary @sebweb3r https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_code.txt

**Comment by sebweb3r** [comment]
I'm not entirely sure of the purpose of the different dictionaries. Is there an explanation somewhere?

**Comment by peternewman** [comment]
In the help, or here:
https://github.com/codespell-project/codespell/blob/00f8ffd23ddd41bb562c4c1ba2f8df24f0f38cd7/codespell_lib/_codespell.py#L40-L51

So the code one (slightly confusingly) is where we put likely code typos, so you don't use that dictionary if you're checking code (if that makes sense). Or more clearly, the informal one "fixes" informal language, so if you run with that dictionary too, it will remove those "misspellings".

**Comment by peternewman** [comment]
@larsoner writing this, should we add "that might be typos" to the end of code too? Also possibly "for making informal words more formal". Essentially those two (and rare) remove those types of words from the text being checked.

**Comment by larsoner** [comment]
Whatever makes it clearer for people is fine by me

**Comment by peternewman** [comment]
Had a go at this in https://github.com/codespell-project/codespell/pull/1793
