### ISSUE TITLE
Mailing list abandoned?

### ISSUE THREAD

**Issue by lurch** [codespell-project/codespell#1662]
In the README there's mention of a mailing list with archives at https://groups.google.com/forum/?fromgroups#!forum/codespell

However at least two of the posts are clearly spam messages, and the last non-spam message was sent almost 4 years ago! Is it time to remove the mention of a mailing list from the README?

**Comment by sebweb3r** [comment]
I think it is time to remove the mailing list.

**Comment by skangas** [comment]
I believe that this issue could be closed with https://github.com/codespell-project/codespell/commit/c26bb28dadb0785b8403fe58a94fddaadcae7e9f.
