### ISSUE TITLE
false positive at boundary of a string literal

### ISSUE THREAD

**Issue by asottile** [codespell-project/codespell#1682]
```python
def test():
    out = ...
    expected = (
        "The exclude pattern 'foo' for check-useless-excludes "
        'does not match any files'
    )
    assert expected == out
```

```console
$ codespell t.py 
t.py:6: files' ==> file's
```

**Comment by sebweb3r** [comment]
I had a look on the dictionary and moved the words, that should cause trouble to the code dictionary. This dictionary is not used automatically and contains typos, that can cause problems with code.

**Comment by peternewman** [comment]
@asottile . Did you have any codespell config set, or is this just out of the box?

**Comment by asottile** [comment]
OOTB
