### ISSUE TITLE
codespell ignores C/C++ tabs ('\t') in strings

### ISSUE THREAD

**Issue by orbitcowboy** [codespell-project/codespell#17]
I found out, that codespell gives wrong answers in case of a tab is used within a C/C++ string. For example:
test.c:

``` c++
int main()
{
    std::cout<< "\tTest\n";
}
```

dict.txt:

```
ttest->test
```

Scanning with test.c with codespell gives a wrong result:

```
$ ../codespell.py dict.txt test.c 
test.c:3: tTest  ==> test
```

**Comment by vinc17fr** [comment]
`\n` should also be ignored.

**Comment by yarikoptic** [comment]
`\t` issue might have been resolved but I keep hitting this eldest ever issue with `\n` once in a while, e.g. on `/tmp/1.c`:

```C
int main()
{
    std::cout<< "\tTest\nin here";
}
```

```shell
❯ codespell --version
2.2.2
❯ codespell /tmp/1.c
/tmp/1.c:3: nin ==> inn, min, bin, nine
```
