### ISSUE TITLE
Feature: Exitcode handling

### ISSUE THREAD

**Issue by daniel-wtd** [codespell-project/codespell#1708]
Hi,

thank you for the nice tool.
It would be awesome, if different exit codes could be supported for "found something" and "found nothing". For me it would be fine, if the tool exits either optional or general with an exit code. This would be a nice feature to integrate it in CI/CD workflows.

Regards

**Comment by larsoner** [comment]
On `master` this behavior was standardized:

https://github.com/codespell-project/codespell/pull/1558

Feel free to see if it takes care of your use case. We just need to release I think.
