### ISSUE TITLE
Escaped characters in strings not ignored in 2.0 version

### ISSUE THREAD

**Issue by diafour** [codespell-project/codespell#1774]
Hello! I use the latest version of codespell in CI. Yesterday everything was ok, but the new release gives errors about escaped characters.

A minimal reproducible example is simple:
```
cat hello.c
#include <stdio.h>

int main() {
  printf("CodeSpell do not ignore escaped chars\nin strings.");
  return 0;
}
```

codespell==1.17.1 sees no problem in that file.

codespell==2.0.0 gives this message:

```
hello.c:4: nin ==> inn, min, bin, nine
```

**Comment by bl-ue** [comment]
I think it would even **better** if codespell intelligently detected a `\` or `\n` at the beginning and skipped it.  Because it's common to make typos in strings.  Of course it should respect your configuration, and there shouldn't be a regression.  Just a thought.

**Comment by jschwartzentruber** [comment]
An easy solution to this is something like:

```
[codespell]
ignore-regex = \\[ns]
```

**Comment by juju4** [comment]
I also see this when working on ARM template (Azure; json files).

Above workaround seems to work well.

multiple related entries
https://github.com/codespell-project/codespell/pull/151
https://github.com/codespell-project/codespell/pull/174
https://github.com/codespell-project/codespell/issues/233
https://github.com/codespell-project/codespell/pull/1422

**Comment by DimitriPapadopoulos** [comment]
This might be widely useful enough to add it the [README.rst](https://github.com/codespell-project/codespell/blob/master/README.rst) page, or to a new "recipes" page.
