### ISSUE TITLE
Travis CI Credits

### ISSUE THREAD

**Issue by peternewman** [codespell-project/codespell#1805]
https://travis-ci.com/organizations/codespell-project/plan

Mixed messages online, we might be able to ask for credits but may not get them. We probably need to look at moving the remaining bits to GitHub Actions...

**Comment by larsoner** [comment]
I suppose we should fix Travis before merging any other PRs. I can make a quick PR to switch to Azure tomorrow probably.

**Comment by peternewman** [comment]
Turns out switching to GH Actions for everything was pretty easy, see #1810. Curiously none of my Travis repos have had the issue so it might be worth reaching out to them, or we could just give up and move on.

**Comment by larsoner** [comment]
> Curiously none of my Travis repos have had the issue so it might be worth reaching out to them, or we could just give up and move on.

It's because I switched us over to travis-ci.com on a beta about a week before they put these limits in place. I think projects on travis-ci.org still have open-source credits available. So not great timing by me with the switch :(

**Comment by peternewman** [comment]
> It's because I switched us over to travis-ci.com on a beta about a week before they put these limits in place. I think projects on travis-ci.org still have open-source credits available. So not great timing by me with the switch :(

Ah you might just have got unlucky then. I'd moved/created stuff before and after and they all seem to have dodge the issue. So maybe they'll sort codespell-project eventually.
