### ISSUE TITLE
Automerge PRs

### ISSUE THREAD

**Issue by peternewman** [codespell-project/codespell#1820]
> Another new feature for the cloud-based git hosting service is auto-merge for pull requests. A pull request in git is a suggested code change that a developer submits for review and approval. Auto-merge lets developers have contributors' pull requests merged into their code base automatically once reviews or status checks have been passed, rather than having a separate merge authorization step.
> 
> This capability will be offered next week as a public beta for public repos and for private repos on Teams and GitHub Enterprise Cloud plans.

Should we turn this on, then we could drive all the dictionary edits by just approved reviews?

**Comment by larsoner** [comment]
Personally I don't bother approving and just click the squash+merge button, it's one click either way. Feel free to enable it if it's a better workflow for you @peternewman (as long as it doesn't mess up mine :) )

**Comment by arm-in** [comment]
Currently, there are many open pull requests.
IMHO, this is not advantageous for the advancement of an open source project. Contributors may get discouraged.

**Comment by larsoner** [comment]
Indeed, maintainer bandwidth is a common problem in OSS. @arm-in you've made a number of PRs, would you be interested in helping maintain / review / merge PRs?

**Comment by peternewman** [comment]
> Personally I don't bother approving and just click the squash+merge button, it's one click either way. Feel free to enable it if it's a better workflow for you @peternewman (as long as it doesn't mess up mine :) )

I've turned it on, but nothing shows up currently and reading in a bit more detail I'm not actually sure how useful it will be.

FWIW this would just be a way to simplify it for "official" maintainers, it wouldn't by itself provide a way for people who weren't maintainers to get things merged quicker.

> Currently, there are many open pull requests.
> IMHO, this is not advantageous for the advancement of an open source project. Contributors may get discouraged.

While I'd agree with you in general, I think it's less critical for dictionary entries (compared to code changes), it's more beneficial that they're curated rather than a free for all. As @larsoner says though, it's a Forth Bridge issue or worse as they just keep coming!

Even if you don't want to maintain @arm-in it would be great if more people could pick up the issues and additions that are often found when reviewing the PRs.

**Comment by peternewman** [comment]
I think I've done a lot of the low-hanging fruit in terms of PRs now.

**Comment by vikivivi** [comment]
@larsoner @peternewman what about fork out the dictionary into an independent project and invite more collaborators to maintain / review / merge PRs ? It would have less impact to the codespell main project?

**Comment by larsoner** [comment]
I'm happy to add maintainers who want their job/role to be (self-)limited to reviewing dictionary PRs and not looking at code changes. People don't have to do both if they don't want to. So I don't think splitting the project would help much.

**Comment by peternewman** [comment]
In the unlikely event we were worried about who had commit access to what, code ownership could allow us to enforce reviews from particular users/teams for the non-dictionary files (or conversely allow dictionary people to just be notified of dictionary changes): https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by arm-in** [comment]
> Indeed, maintainer bandwidth is a common problem in OSS. @arm-in you've made a number of PRs, would you be interested in helping maintain / review / merge PRs?

Thank you for the offer. I'm not a native speaker, and we had different perspectives in the past about what should be included in the dictionary and what not. So I guess I'm not a good choice as a maintainer. Contributor yes. Maybe reviewer of dictionary entries.

**Comment by peternewman** [comment]
> Thank you for the offer. I'm not a native speaker, and we had different perspectives in the past about what should be included in the dictionary and what not. So I guess I'm not a good choice as a maintainer. 

I'm not sure there's always consensus between  the current commiters @arm-in 

> Contributor yes. Maybe reviewer of dictionary entries.

More reviews would certainly help @arm-in , although you don't actually need any special permissions for that. More eyeballs would spot more potential alternatives, or linked extensions that might be missing. As @larsoner was saying about bandwidth, it would be nice to just drop into a review that a few people have spotted the obvious stuff on so it would then just need a second opinion before merging.

> I'm not a native speaker

That could be both an advantage and a disadvantage. You might not know some words to spot alternatives, but you might double-check stuff that might pass me by as looking okay.

**Comment by peternewman** [comment]
Automerge is on and in use, so closing this.
