### ISSUE TITLE
Add option to verify if a word is spelled correctly

### ISSUE THREAD

**Issue by kayhayen** [codespell-project/codespell#1840]
Recently, a typo was reported against Nuitka that I was uncertain about, if codespell thinks the word is correct or not, or if it is because of the code context somehow not checked. I even got to doubt if my wrapper handles stuff correctly in case of spelling errors found.

An option to check a single word would have worked best in that case. Something like `codespell --word resourcs` would have helped me there.

**Comment by vikivivi** [comment]
Typical spelling checker uses databases containing all the correctly spelled words to check document.
Codespell been atypical, uses databases containing some of the commonly misspelled words to check document.

Since misspelled word `resourcs` hasn't been entered into codespell database, codespell will never report back as error until `resourcs` is been part of it's database. Try this:

```sh
echo resourcs | codespell -
echo rescources | codespell -
```

To verify word is spelled correctly, you might better off using something else. Personally I am using the following script which uses aspell, hunspell, ispell.

```sh
./check-misspell.sh "resourcs apple orange"

/usr/bin/look resourcs /usr/share/dict/british-english-huge
/usr/bin/look resourc  /usr/share/dict/british-english-huge
```

```sh
#!/bin/sh
# script usage: ./check-misspell.sh "resourcs apple orange"

spelling_check_word() {
	WORD="$1"

	echo "### hunspell: en_GB"
	echo "$WORD" | hunspell -a -d en_GB | grep "^\&\|^\#"

	echo "### hunspell: en_US"
	echo "$WORD" | hunspell -a -d en_US | grep "^\&\|^\#"

	echo "### aspell: en_GB"
	echo "$WORD" | aspell -a -d en_GB | grep "^\&\|^\#"

	echo "### aspell: en_US"
	echo "$WORD" | aspell -a -d en_US | grep "^\&\|^\#"

	#echo "### ispell: british-insane"
	echo "### ispell: british-huge"
	echo "$WORD" | ispell -a -B -d british-huge | grep "^\&\|^\#"

 	#echo "### ispell: american-insane"
	echo "### ispell: american-huge"
	echo "$WORD" | ispell -a -B -d american-huge | grep "^\&\|^\#"

	echo "### spell: "
	echo "$WORD" | spell
}

spelling_check_word "$1"
```

**Comment by kayhayen** [comment]
No, this is explicitely to know if codespell does know a word or not, and what ideally replacements there are. I had no way of knowing after I verified that this is a mistake, I didn't know if codespell was not reporting it, because of something else, or if it was unaware of the error.

Currently I have no way of querying the dictionary other than to codespell a file with just the identifier and even then.

**Comment by vikivivi** [comment]
See below, codespell returned 0 for both cases. If codespell return 0, this mean codespell do not know both words. Codespell is not aware that there is a misspell in the second case and a correct spelling in the first case.
```sh
echo apple | codespell -
echo $?
echo appppppple | codespell -
echo $?
```

**Comment by kayhayen** [comment]
Ok, didn't think of stdin, so my suggestion is pointless I guess.
