### ISSUE TITLE
The whitelist does not work when words have mixed case

### ISSUE THREAD

**Issue by xsmq** [codespell-project/codespell#1860]
### 1. Unused whitelist
$ codespell -q 7  mindspore/mindspore/lite/tools/converter/parser/tf
mindspore/mindspore/lite/tools/converter/parser/tf/tf_merge_parser.cc:39: MergeT ==> merge
mindspore/mindspore/lite/tools/converter/parser/tf/tf_activation_parser.cc:66: shoud ==> should

![image](https://user-images.githubusercontent.com/23582707/105269936-db44a900-5bcf-11eb-8163-0e6dfb674981.png)

#### (1) MergeT
$ cat codespell.txt 
MergeT
shoud

$ codespell -q 7 -I codespell.txt mindspore/mindspore/lite/tools/converter/parser/tf
mindspore/mindspore/lite/tools/converter/parser/tf/tf_merge_parser.cc:39: MergeT ==> merge

![image](https://user-images.githubusercontent.com/23582707/105270369-9b31f600-5bd0-11eb-8af0-8cbf2a6031e9.png)

#### (2) nNumber
$ cat codespell.allow 
MergeT
nNumber

$ codespell -q 7 -I codespell.allow mindspore/mindspore/ccsrc/minddata/dataset/engine/connector.h
mindspore/mindspore/ccsrc/minddata/dataset/engine/connector.h:151: nNumber ==> number
mindspore/mindspore/ccsrc/minddata/dataset/engine/connector.h:152: nNumber ==> number

![image](https://user-images.githubusercontent.com/23582707/105276424-4f854980-5bdc-11eb-9420-924c9ac281e7.png)

#### (3) REALEASE
$ cat codespell.allow 
pyhton
REALEASE

$ codespell -q 7 -I codespell.allow mindspore/mindspore/lite/examples/train_lenet/README.md
mindspore/mindspore/lite/examples/train_lenet/README.md:67: REALEASE ==> RELEASE
mindspore/mindspore/lite/examples/train_lenet/README.md:68: betweeen ==> between
mindspore/mindspore/lite/examples/train_lenet/README.md:72: followings ==> following
mindspore/mindspore/lite/examples/train_lenet/README.md:78: paramaters ==> parameters

![image](https://user-images.githubusercontent.com/23582707/105277226-fcac9180-5bdd-11eb-843b-3f8d6f12d199.png)

**Comment by r3econ** [comment]
I'm experiencing the same problem. Makes using this tool in production impossible

**Comment by peternewman** [comment]
Hi @xsmq ,

As mentioned to @r3econ in https://github.com/codespell-project/actions-codespell/issues/29 , from the main codespell help ( https://github.com/codespell-project/codespell#readme ):

> Important note: The list passed to -I is case-sensitive based on how it is listed in the codespell dictionaries.

> ### 2. Add whitelist
> #### (1) MergeT

```
grep -iIR merget codespell_lib/data/
codespell_lib/data/dictionary.txt:merget->merge
```

> #### (2) nNumber
> 
> $ cat codespell.allow
> MergeT
> nNumber

```
grep -iIR nnumber codespell_lib/data/
codespell_lib/data/dictionary.txt:nnumber->number
```

> #### (3) REALEASE
> 
> $ cat codespell.allow
> pyhton
> REALEASE

```
grep -iIR ^realease codespell_lib/data/
codespell_lib/data/dictionary.txt:realease->release
codespell_lib/data/dictionary.txt:realeased->released
codespell_lib/data/dictionary.txt:realeases->releases
```

So you want these in your codespell.allow:
```
merget
nnumber
realease
```

**Comment by xsmq** [comment]
OK，thanks.

**Comment by peterjc** [comment]
I just struggled with this with an all capital term, having initially expected this to mean case sensitive to match the input file. That does seem a more intuitive behaviour - although a change to the tool.

**Comment by peternewman** [comment]
> I just struggled with this with an all capital term, having initially expected this to mean case sensitive to match the input file. 

@peterjc we'd welcome suggestions for how to make the existing help file more clear/less confusing:

> Important note: The list passed to -I is case-sensitive based on how it is listed in the codespell dictionaries.

> That does seem a more intuitive behaviour - although a change to the tool.

If it had to match the input file, then if I had this input:
```
SPELING TOOLS
There are lots of tools to catch spelings available
```

Then I'd need to add two ignore entries for the two cases that appear in the input.

I'm not entirely sure of the history of why we don't just do a case-insensitive comparison, but it would prevent some classes of typos being entered and therefore detected (e.g. names being in lower case).
