### ISSUE TITLE
Add a way to ignore line endings when matching lines from `--exclude-file`

### ISSUE THREAD

**Issue by Jackenmen** [codespell-project/codespell#1888]
This can be especially when repository is used on Windows with git's `core.autocrlf` set to `true` as then some files can have CRLF line endings locally even though they're checked out into git with LF endings. This mixing can therefore cause `codespell` to not ignore some lines if the line endings in `--exclude-file` differ from line endings in the file with spelling issue.

**Comment by peternewman** [comment]
Yeah I'd agree, the line ending should be irrelevant within any of our config files (--exclude-file, --ignore-word-list) etc.

**Comment by DimitriPapadopoulos** [comment]
I'm reopening this because #1889 because the new `rstrip()` might remove not only newlines but also spaces. We need to make sure everything works as expected.

**Comment by DimitriPapadopoulos** [comment]
It seems to be working as expected for me:
```console
$ file exclude-file1.txt exclude-file2.txt test1.txt test2.txt 
exclude-file1.txt: ASCII text
exclude-file2.txt: ASCII text, with CRLF line terminators
test1.txt:         ASCII text
test2.txt:         ASCII text, with CRLF line terminators
$ 
$ codespell test1.txt test2.txt 
test1.txt:1: accepecting ==> accepting
test2.txt:1: accepecting ==> accepting
$ 
$ codespell -x exclude-file1.txt test1.txt test2.txt 
$ 
$ codespell -x exclude-file2.txt test1.txt test2.txt 
$ 
```
However, the above works whatever spaces we add at the end of any of the above files. It looks like all trailing newlines **and** spaces are **not** taken into account when matching lines. Perhaps spaces **should** be taken into account when matching.

**Comment by Jackenmen** [comment]
I'm pretty sure that was an intentional choice, trailing space is a nightmare to deal with and requiring that the line in ignore file contains that space doesn't seem to actually benefit you in any way since the contents of the line are still identical.
