### ISSUE TITLE
Collaborators?

### ISSUE THREAD

**Issue by bl-ue** [codespell-project/codespell#1924]
Open to new collaborators?  I'd love to help maintain.

I'd like to help review PRs pertaining to the dictionary, as well as changes to the codespell core, as I'm working with Python a lot these days and have developed strong skills ;)

**Comment by peternewman** [comment]
No objections here, but probably more an @larsoner or others question. I certainly didn't sign up for endless dictionary reviews!

I would say even without commit rights, others can still review PRs and point out issues, if it meant I could just take a final glance at a dictionary PR and merge it would be great, after others had already picked up the missing variations or stuff in the wrong dictionary file or missing suggestions.

**Comment by bl-ue** [comment]
ping @larsoner — could I become a collaborator? :)

**Comment by pabs3** [comment]
I haven't been active on codespell for a long time, I guess @larsoner should make the decision. In the meantime, @peternewman's suggestions sound good to me.

**Comment by bl-ue** [comment]
🏓 @larsoner again :)

**Comment by larsoner** [comment]
Invited!

**Comment by bl-ue** [comment]
Thank you! Accepted.  Can I join the org, too?

**Comment by bl-ue** [comment]
Cool, I accepted the invitation to the organization.  But I don't have write access to any other repos 🤔

**Comment by larsoner** [comment]
What else do you need write access to?

**Comment by bl-ue** [comment]
I don't actually _need_ write access to anything else; however, it would be nice to be able write to  them in all in case someone opened a PR 😉

**Comment by larsoner** [comment]
Made a team with write permissions (less than blanket admin that Adm has) and added you to it!

**Comment by bl-ue** [comment]
codespell is a wonderful project, and I'd really like to see it keep growing, and I'm willing donate (significant) amounts of time towards that goal.

**Comment by peternewman** [comment]
There's also triage, I don't know if that lets you merge a PR, or just label them.
