### ISSUE TITLE
Convert printf-style printing to f-strings

### ISSUE THREAD

**Issue by bl-ue** [codespell-project/codespell#1946]
Does anyone mind if I change the codebase to using the more modern (Python 3.6+) f-strings for printing, instead of the old C printf-style?  With a lot of format parameters, the printf-style can get very ugly and hard to read, and the f-string style also allows for more powerful formatting capabilities.

old (printf-style):
```python
a = 'World'
print('%s, %s!' % (a, b)) // Hello, World!
```

new (f-string-style):
```python
a = 'Hello'
b = 'World'
print(f'{a}, {b}!') // Hello, World!
```

For a real example from the source:

old (printf-style):
```python
print("%(FILENAME)s: %(WRONGWORD)s"
        " ==> %(RIGHTWORD)s%(REASON)s"
        % {'FILENAME': cfilename,
            'WRONGWORD': cwrongword,
            'RIGHTWORD': crightword, 'REASON': creason})
```

new (f-string-style):
```python
print(f"{cfilename}: {cwrongword} ==> {crightword}{creason}")
```

cc @peternewman @larsoner

**Comment by peternewman** [comment]
Well it would break Python 3.5 compatibility:
https://github.com/codespell-project/codespell#requirements

I don't know if that's a big issue for people.

What happens with arrays and other things like that, or does it cope with them?

**Comment by bl-ue** [comment]
Python 3.5 is EOL — not supported.  I'll open a PR to bump the min version to Python 3.6.

>What happens with arrays and other things like that, or does it cope with them?

The two different mechanisms appear to output identically:

```python
>>> print(f'{[1,2,3]}')
[1, 2, 3]
>>> print('%s' % [1,2,3])
[1, 2, 3]
>>> print('%s' % vars())
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}
>>> print(f'{vars()}')
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}
>>> 
```

**Comment by bl-ue** [comment]
So wdyt @peternewman?

**Comment by peternewman** [comment]
Sorry I didn't reply @bl-ue .

> > What happens with arrays and other things like that, or does it cope with them?
> 
> The two different mechanisms appear to output identically:

I was meaning more if you wanted to say output only the second item in the array for example, is that even possible with the f-strings stuff? I'll admit I haven't looked at all.
