### ISSUE TITLE
format of FILE as in --exclude-file=FILE

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2046]
What is the format of **FILE** as in `--exclude-file=FILE`?

Is it perhaps of the form "file:line"? If so, I suggest fixing the help message from:
```
  -x FILE, --exclude-file=FILE
                        FILE with lines that should not be changed
```
to:
```
  -x FILE, --exclude-file=FILE
                        FILE with file:line pairs that should not be changed
```
That would avoid misunderstandings such as https://github.com/codespell-project/codespell/issues/1601#issuecomment-663634656 and https://github.com/codespell-project/actions-codespell/issues/33#issuecomment-903241243.

**Comment by DimitriPapadopoulos** [comment]
After reading the source code, It appears it's really simple line numbers in the file, not specific to a file. So if you want to exclude line 100 of a specific file, you cannot but exclude line 100 of all files.

**Comment by peternewman** [comment]
It's the whole line, not the line number. See #2052 for work to fix this.

**Comment by DimitriPapadopoulos** [comment]
Ah, I see. Sorry about that. Then let's follow up in #2052.
