### ISSUE TITLE
"keyserver" is correct

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2084]
It looks like _keyserver_ is a correct technical word in cryptography. For example, the [Wikipedia _key server_ entry](https://en.wikipedia.org/wiki/Key_server_(cryptographic)) has 27 occurrences of _key server_ and 31 occurrences of _keyserver_.

On Google, [1,140,000 hits for _keyserver_](https://www.google.com/search?q=keyserver) and [537,000 hits for _key server_](https://www.google.com/search?q=%22key+server%22) - but it's true that a large part of the _keyserver_ hits are command line examples, code, URLs.

See discussion in https://github.com/numpy/numpy/pull/19911#discussion_r713107622.

**Comment by peternewman** [comment]
I'd dispute this somewhat, Wikipedia seems to just switch arbitrarily between the two without defining either one or being consistent.

The more interesting this is that a company copyrighted it (in the software licensing sense):
https://en.wikipedia.org/wiki/Software_license_server

Also this is in the code dictionary already, we wouldn't generally recommend running that over a codebase without careful checking of the results. Outside of code it's still likely to be a typo for the two word phrase.

**Comment by peternewman** [comment]
Looking at the PGP page, and the phrasing on the general Wikipedia page, I wonder if it's a defined term in terms of PGP:
https://en.wikipedia.org/wiki/Pretty_Good_Privacy

**Comment by DimitriPapadopoulos** [comment]
I agree, _keyserver_ is mostly found in contexts associated to PGP and sometimes to license servers.

It's just that there are so many occurrences of `keysever` out there - more than occurrences of `key server` - that I doubt they will ever be considered typos by projects maintainers. At least that my impression after  suggesting patches with `keyserver->key server` to a few projects.

**Comment by matkoniecz** [comment]
> Wikipedia seems to just switch arbitrarily between the two without defining either one or being consistent.

I would consider it as indication that both forms are correct.

> developed their trademarked KeyServer software license

In such case wide use of "keyserver" and "KeyServer" when referring to generic keyservers would help with turning it into https://en.wikipedia.org/wiki/Generic_trademark

**Comment by DimitriPapadopoulos** [comment]
My _understanding_ of the rules is that we use formal, curated dictionaries as references – but I do not make the rules. It looks like we haven't been able to find `keyserver` in such dictionaries.

Again, perhaps the way out can be to clarify the rules, in the README or help – not sure who should do that.

As I already wrote, I can fully understand your merge request here. However, each individual exception to a rule, generates questions for other individual cases. Some argue for and some against. It all takes time nobody has. In any case, I will not decide myself in this specific case.

And again, do remember, codespell just provides suggestions and take suggestions with a grain of salt. This is not a law enforcement agency coming after misspells :smile:

**Comment by DimitriPapadopoulos** [comment]
Perhaps it should be moved to `dictionary_rare.txt` instead of `dictionary_code.txt`, but that would probably be even worse because `dictionary_rare.txt` is a default dictionary, unlike `dictionary_code.txt`.

**Comment by matkoniecz** [comment]
> My understanding of the rules is that we use formal, curated dictionaries as references – but I do not make the rules. It looks like we haven't been able to find keyserver in such dictionaries.

In such case sorry for making PR that is not fixing an actual problem - though ideally it would be documented somewhere.

Still, for technical terms I would not fully trust "formal, curated dictionaries".
