### ISSUE TITLE
tox.ini config file

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2086]
What about adding `tox.ini` to the default locations of the config file, in addition to `setup.cfg` and `.codespellrc`?

Some projects such as [python-versioneer](https://github.com/python-versioneer/python-versioneer) have a `tox.ini` file but no `setup.cfg` file.

**Comment by peternewman** [comment]
> Some projects such as [python-versioneer](https://github.com/python-versioneer/python-versioneer) have a `tox.ini` file but no `setup.cfg` file.

We've been so slow python-versioneer has both now, ironically just to version itself!
https://github.com/python-versioneer/python-versioneer/commit/24df886b7e222ea226a83a27c22279b16fc5a393#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52

**Comment by buhtz** [comment]
Can be closed. Not relevant anymore because of pyproject.toml. See comment in un-merged but closed PR #2087
