### ISSUE TITLE
Remove `# -*- coding: utf-8 -*-`?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2099]
In Python 3, the [default source file encoding is UTF-8](https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations). As far as the Python interpreter is concerned we could remove `# -*- coding: utf-8 -*-`.

Yet the encoding declaration might be useful to some IDEs, especially on Windows which still seems to be enforcing Windows-1252 as the default encoding on "Western" locales. On the other hand, VS tends to write into **UTF-8-BOM** (with an initial BOM) so we're doomed anyway!

**Comment by skangas** [comment]
This line is used by Emacs on some platforms. I see no benefit to removing it.

**Comment by DimitriPapadopoulos** [comment]
Emacs knows it load a Python file and that Python files are UTF-8 files, doesn't it?

**Comment by skangas** [comment]
I'm on GNU/Linux using a UTF-8 locale, and there the answer is that it is _not_ needed. AFAIU, the story might be different on other platforms. On the other hand, I guess it could be removed and if anyone has problems they can open a new issue.

**Comment by skangas** [comment]
But I guess this was removed in f0b562ea46370b383f101a775094f5e9d6d29aec, so I think this issue could be closed.
