### ISSUE TITLE
include tests/documentation of skipped words

### ISSUE THREAD

**Issue by matkoniecz** [codespell-project/codespell#2148]
Maybe it would be useful to have edits removing word (like #2084) putting them on list of "bad ideas" with an explanation?

So if someone in future would want to add it then it would be automatically caught by CI and provided explanation why it is not a typo? The same for say `protecten` or #2144 

Note that while for added words `blame` works well it does not work for discovering what was removed in the past.

(or is it not a real problem and in rare cases where words was added back people will simply complain and it is a sufficient control mechanism?)

**Comment by peternewman** [comment]
> Maybe it would be useful to have edits removing word (like #2084) putting them on list of "bad ideas" with an explanation?

As mentioned in the corresponding issue, I'm not necessarily convinced that should go, although something else did re-appear recently but I can't remember what it was.

> So if someone in future would want to add it then it would be automatically caught by CI and provided explanation why it is not a typo? The same for say `protecten` or #2144
> 
> Note that while for added words `blame` works well it does not work for discovering what was removed in the past.

As long as stuff just moves to a more appropriate dictionary, then you can blame on that end (which also works in the web UI, whereas the main dictionary is too big that it fails).

Personally I'd hope we could automate it more by checking stuff against further external dictionaries/word lists and flagging when someone tries to add a valid word.

If we did need a separate history list, then just adding them to another block list dictionary which was never used apart from to track problem words should do the job with practically no development effort.

> (or is it not a real problem and in rare cases where words was added back people will simply complain and it is a sufficient control mechanism?)

I've certainly caught stuff when its been added back and tripped up my CI.

**Comment by matkoniecz** [comment]
OK, it appears that it is likely not worth doing
