### ISSUE TITLE
Check also filenames

### ISSUE THREAD

**Issue by matkoniecz** [codespell-project/codespell#2155]
There is a closed "Filenames of empty files are not checked" #1532

but for me filenames are not checked

```
mateusz@grima:~/Desktop/tmp$ touch "ned speling cheeck.md"
mateusz@grima:~/Desktop/tmp$ codespell 
mateusz@grima:~/Desktop/tmp$ ls > test.txt
mateusz@grima:~/Desktop/tmp$ codespell 
./test.txt:1: ned ==> need
./test.txt:1: speling ==> spelling
```

I also tested and filenames of nonempty files are also not checked

**Comment by peternewman** [comment]
I assume you've turned on the requisite option:
https://github.com/codespell-project/codespell/blob/fabf9eb2b902a2538d6a04ada732c3968595e355/codespell_lib/_codespell.py#L378-L380

**Comment by matkoniecz** [comment]
No, I actually pasted full commands. Sorry.
