### ISSUE TITLE
oce->one?

### ISSUE THREAD

**Issue by matkoniecz** [codespell-project/codespell#2156]
It appears that oce is not a word in English

https://en.wiktionary.org/wiki/oce

https://www.google.com/search?hl=en&q=%22oce%22

https://duckduckgo.com/?t=ffab&q=%22oce%22&ia=web

**Comment by peternewman** [comment]
If you're suggesting this as a new correction, the easiest thing is to just open a PR, people can make comments/suggestions or it can just be merged as is. I assume you've found oce in some code? Does it look like one from the context?
