### ISSUE TITLE
Misidentifying a matplotlib function as spelling error

### ISSUE THREAD

**Issue by banesullivan** [codespell-project/codespell#2185]
Add `plt.hist` anywhere in your code and you'll get the following correction suggestion:

```
hist ==> heist, his
```

The fact that `codespell -w` would overwrite actual code seems highly problematic to me (this is a bad example because `-w` won't do anything in this particular case since there are two possibilities).

To reproduce:

```py
$ mkdir foo; cd foo; echo "import matplotlib.pyplot as plt;plt.hist([0,1,1]);" >> foo.py; codespell .
./foo.py:1: hist ==> heist, his
```

**Comment by DimitriPapadopoulos** [comment]
That's expected. Nothing on the documentation tells otherwise. Just add `hist` to the lost of words to allow.

**Comment by DimitriPapadopoulos** [comment]
In short, I would never run `codespell -w` automatically, without reviewing the suggestions, either interactively, or after running `codespell -w` and before committing.

I believe you won't find (yet?) software that can automatically fix spelling errors without human supervision.

Moreover, `codespell` is programming language agnostic, it processes Python, C or documentation the same way. That's debatable, of course, but as a result `codespell` can be run on any code or documentation in text format (but that I mean not binary format as a Word 97-2003 file for example).

**Comment by banesullivan** [comment]
For some reason I was under the impression it only spellchecked comments and strings

**Comment by banesullivan** [comment]
If this is expected behavior, feel free to close the issue. I'll just add a +1 for #1147

**Comment by banesullivan** [comment]
> add hist to the list of words to allow.

Can I add `plt.hist` as an allowed word? Adding `hist` to allowed words would nullify the `hist ==> heist, his` dictionary entry

**Comment by DimitriPapadopoulos** [comment]
I don't know. Do give `plt.hist` a try, otherwise you will add `hist` to the list of allowed words. That's what I do: not perfect, but then codespell cannot and will not catch all typos anyway, only common ones:
* it relies on a dictionary of typos and not a dictionary of valid words, and that dictionary of typos is not complete,
* some typos might be valid words.

**Comment by peternewman** [comment]
> Can I add `plt.hist` as an allowed word?

No, but you can use the new regex ignore option to effectively remove plt.hist from the data Codespell looks at and do the same thing.

> Adding `hist` to allowed words would nullify the `hist ==> heist, his` dictionary entry

Yep, hence @DimitriPapadopoulos about needing to review it manually. You can only skip it everywhere, use the regex ignore option, or skip the entire line and hope you didn't miss any other typos in the line.

Is .hist a permanent/builtin matlabplot extension/function (for doing a histogram or whatever), or just what you happen to have chosen like foo? If the former then feel free to submit a PR moving this particular typo from the dictionary file to the code dictionary and it's then disabled by default (but then it still won't check it in your comments...).

**Comment by banesullivan** [comment]
> Is .hist a permanent/builtin matlabplot extension/function

I don't think `plt.hist` is going anywhere.

I do think it makes sense to have `hist ==> heist, his` in the codespell database so I'm not going to pursue any change in that regard.

It now makes sense to me why is was showing as an error and I think my bigger request here is for #1147 and this is a side effect of sorts until that feature so I'm going to close this issue.

**Comment by DimitriPapadopoulos** [comment]
Yes, [`matplotlib.pyplot.hist`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html) is a matplotlib function, and it's extensively used in scientific Python software.

**Comment by DimitriPapadopoulos** [comment]
Note that hist is already in the **rare** dictionary, because it is a valid word:
https://www.merriam-webster.com/dictionary/hist
https://www.collinsdictionary.com/dictionary/english/hist
https://www.thefreedictionary.com/hist

**Comment by peternewman** [comment]
Thanks for the clarification, then I think we should take the next step and move it to the code dictionary then, so it's effectively disabled by default unless people chose to add that dictionary.

Similar to the other entries in there such as the assembly command movei:
https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_code.txt

We're not suggesting removing it @banesullivan , just making it more targeted and therefore reducing the risk of people accidentialy breaking their code by running codespell.
