### ISSUE TITLE
warn on running -i without -w

### ISSUE THREAD

**Issue by matkoniecz** [codespell-project/codespell#2190]
I was a bit confused and needed to reread entire man page to spot that to have interactive editing (necessary to avoid editing `.git` folder) I need to enable not only `-i`

**Comment by peternewman** [comment]
Why aren't you just skipping .git folders again?

I'd probably go further and -i should imply -w, as like you said, I can't see any reason to ask anything interactively if you aren't going to save the answers.

**Comment by matkoniecz** [comment]
> I'd probably go further and -i should imply -w, as like you said, I can't see any reason to ask anything interactively if you aren't going to save the answers.

+1

> Why aren't you just skipping .git folders again?

I am running one big aliased filter on all my files at once.

As this is combination of multiple commands (including `grep -v`) I cannot apply `-i -w` to it.

**Comment by peternewman** [comment]
> > I'd probably go further and -i should imply -w, as like you said, I can't see any reason to ask anything interactively if you aren't going to save the answers.
> 
> +1

Actually found one possible reason not to in https://github.com/codespell-project/codespell/blob/ea9bfe3e13ca85addf0b0f65098ec3cbe99ef8d0/README.rst#usage

> Not running with -w flag is the same as doing a dry run.

> > Why aren't you just skipping .git folders again?
> 
> I am running one big aliased filter on all my files at once.
> 
> As this is combination of multiple commands (including `grep -v`) I cannot apply `-i -w` to it, so I run `codespell -i 3` (without `-w` so I become confused). Though the same would apply if there is large amount of typos, including some multiple selection ones and some possibly false positives.

I still don't really follow, but :shrug: . If you use things like find (if you can't use our skip directly) to generate a list of files to check, and then our skip options to avoid particular typos, it should probably be possible I'd imagine. Or just run codespell on each file/folder where you find typos.

**Comment by DimitriPapadopoulos** [comment]
Closed by #3340.
