### ISSUE TITLE
Rehabilitate bale out

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2217]
While "_bail out_" is by far more common, "_bale out_" is correct in UK English. I would suggest removing "_bale_" even from the **rare** dictionary.
* [Oxford dictionary](https://www.oxfordlearnersdictionaries.com/definition/english/bale-out)
* [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/bale-out)

**Comment by peternewman** [comment]
I'm a Brit and I didn't even realise bale was used in that context, I've only ever known it as the big straw thing in a field.

I assume you're referring to:
https://github.com/codespell-project/codespell/blob/c7d77388398e11111564f719590c35fdfe235aaf/codespell_lib/data/dictionary_rare.txt#L13

My suspicion would be the able typo would be more likely than bale being used. Also suggesting bail as a correction will stop it auto-fixing it, which would hopefully be enough?

**Comment by DimitriPapadopoulos** [comment]
The thing is, another Brit does insist on writing _bale out_ :smile:
https://git.tartarus.org/?p=simon/putty.git;a=commit;h=8ff26fd9e50f7e0adc0cc0276f44748311839714

More generally, I do see [54,547 occurrences of _bale out_](https://github.com/search?q=%22bale+out%22&type=code) in GitHub, vs. [892,481 occurrences of mere _bale_](https://github.com/search?q=bale&type=code) (often in the sense of bale of cotton as far as I can see).

I do agree that changing to `bale->able, bail` would improve the situation anyway, enough to keep it in the _rare_ dictionary.

**Comment by peternewman** [comment]
Yeah the cotton is the same meaning as the hay in the field one.
