### ISSUE TITLE
Missing capitalization with more than one suggested fix

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2222]
With this example file:
```sh
$ cat > file
Abourt time!
$ 
```
Here is the current output:
```
file:1: Abourt ==> Abort, about
```
Here is the output I would expect:
```
file:1: Abourt ==> Abort, About
```
Note the missing capitalization of the second (and subsequent) suggested fix `about`.

**Comment by peternewman** [comment]
This issue is a duplicate of #1883 (although it took me a while to find it even knowing it existed)!
