### ISSUE TITLE
Non-ASCII characters in dictionary

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2224]
The last lines of `dictionary.txt` look puzzling at first sight:
https://github.com/codespell-project/codespell/blob/bdcf7a62a2152be3adc4fea27dfb0780bd1efa18/codespell_lib/data/dictionary.txt#L33750-L33759

For example, in `сontain->contain` the wrong word doesn't _look_ like a typo and the fix _looks_ identical to the wrong word. A binary dump show that the first character in the wrong word is not a LATIN SMALL LETTER C, but a CYRILLIC SMALL LETTER ES,  U+0441 coded as `d1 81` in UTF-8:
```
$ tail -8 codespell_lib/data/dictionary.txt  | hexdump -C
00000000  d1 81 6f 6e 74 61 69 6e  2d 3e 63 6f 6e 74 61 69  |..ontain->contai|
00000010  6e 0a d1 81 6f 6e 74 61  69 6e 65 64 2d 3e 63 6f  |n...ontained->co|
00000020  6e 74 61 69 6e 65 64 0a  d1 81 6f 6e 74 61 69 6e  |ntained...ontain|
00000030  65 72 2d 3e 63 6f 6e 74  61 69 6e 65 72 0a d1 81  |er->container...|
[...]
```

This is a new class of typos, which would perhaps benefit from a mechanism of its own. For example, compile a list of [homoglyphs](https://en.wikipedia.org/wiki/Homoglyph), in our case non-ASCII characters that look _visually_ identical to ASCII characters, and identify words that contain **both** these specific non-ASCII characters, and ASCII characters. We can find lists of homoglyphs in articles on [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack). Or perhaps simpler, just detect words that contain both ASCII and non-Latin characters.

Maintaining these typos in the main dictionary is... puzzling!

**Comment by DimitriPapadopoulos** [comment]
Package [homoglyphs](https://pypi.org/project/homoglyphs/) is available to generate the list of homoglyphs. Could use it at build time or run time.

Because the above module is not maintained anymore, build time is good enough, faster and simpler.

**Comment by arm-in** [comment]
See also
https://github.com/codespell-project/codespell/issues/2007

**Comment by DimitriPapadopoulos** [comment]
Indeed, this is a duplicate of #2007. Sorry about that.

I will therefore be closing this one.
