### ISSUE TITLE
Tests do not work locally

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2225]
I get this error when running `make check` locally:
```
$ make check
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=codespell_lib --cov-report=
  inifile: /my/path/codespell/setup.cfg
  rootdir: /my/path/codespell

make: *** [Makefile:21: check-dictionaries] Error 4
$ 
```
It looks like I need the [pytest-cov](https://pypi.org/project/pytest-cov/) package:
* [py.test: error: unrecognized arguments: --cov=ner_brands --cov-report=term-missing --cov-config](https://stackoverflow.com/questions/26589990/py-test-error-unrecognized-arguments-cov-ner-brands-cov-report-term-missi#26590668)

I can install it with `pip3 install pytest-cov`. My question is, is there a simple command to install all "dev" requirements?
https://github.com/codespell-project/codespell/blob/bdcf7a62a2152be3adc4fea27dfb0780bd1efa18/setup.py#L62-L64

**Comment by DimitriPapadopoulos** [comment]
Now that dependencies have been installed:
```
$ pip3 list | grep pytest
pytest                     4.6.9
pytest-cov                 3.0.0
pytest-dependency          0.5.1
$ 
```
I am still getting this error message:
```
$ make check
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=codespell_lib --cov-report=
  inifile: /volatile/src/codespell/setup.cfg
  rootdir: /volatile/src/codespell

make: *** [Makefile:21 : check-dictionaries] Error 4
$ 
```
Any clue?

**Comment by DimitriPapadopoulos** [comment]
About the first question, I had missed the answer is in the [README](https://github.com/codespell-project/codespell/blob/master/README.rst). I was looking under the wrong paragraph, [Requirements](https://github.com/codespell-project/codespell/blob/master/README.rst#requirements) instead of [Development Setup](https://github.com/codespell-project/codespell/blob/master/README.rst#development-setup):

> You can install required dependencies for development by running the following within a checkout of the codespell source:
> ```
> pip install -e ".[dev]"
> ```
> To run tests against the codebase run:
>
> ```
> make check
> ```

**Comment by DimitriPapadopoulos** [comment]
The second question stands:
```
$ pytest codespell_lib
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=codespell_lib --cov-report=
  inifile: /my/path/codespell/setup.cfg
  rootdir: /my/path/codespell
$ 
```
While re-installing the dependencies, I noticed:
```
$ pip3 install pytest pytest-cov pytest-dependency --user
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages (4.6.9)
Collecting pytest-cov
  Using cached pytest_cov-3.0.0-py3-none-any.whl (20 kB)
Collecting pytest-dependency
  Using cached pytest_dependency-0.5.1-py3-none-any.whl
Requirement already satisfied: more-itertools>=4.0.0 in /usr/lib/python3/dist-packages (from pytest) (4.2.0)
Requirement already satisfied: coverage[toml]>=5.2.1 in /home/dimitri/.local/lib/python3.8/site-packages (from pytest-cov) (6.2)
Requirement already satisfied: tomli in /home/dimitri/.local/lib/python3.8/site-packages (from coverage[toml]>=5.2.1->pytest-cov) (2.0.0)
Installing collected packages: pytest-dependency, pytest-cov
Successfully installed pytest-cov-3.0.0 pytest-dependency-0.5.1
$ 
```
Actually, pytest is installed as a Debian package:
```
$ dpkg -l | grep pytest
ii  python-pytest                              4.6.9-1                               all          Simple, powerful testing in Python
ii  python3-pytest                             4.6.9-1                               all          Simple, powerful testing in Python3
$ 
```
Unfortunately, it looks like the `pytest` executable from the Debian package is not aware of the `pytest-cov` module installed with `pip`. Uninstalling the Debian `pytest` packages and reinstalling with `pip`:
```
$ sudo apt purge python-pytest python3-pytest
Reading package lists... Done
Building dependency tree       
Reading state information... Done
[...]
Removing python-pytest (4.6.9-1) ...
Removing python3-pytest (4.6.9-1) ...
Processing triggers for man-db (2.9.1-1) ...
$ 
$ pip3 install pytest --user
Collecting pytest
  Downloading pytest-6.2.5-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 19.6 MB/s            
Collecting py>=1.8.2
  Downloading py-1.11.0-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 12.7 MB/s             
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 8.1 MB/s              
Collecting iniconfig
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: attrs>=19.2.0 in /usr/lib/python3/dist-packages (from pytest) (19.3.0)
Requirement already satisfied: toml in /usr/lib/python3/dist-packages (from pytest) (0.10.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging->pytest) (2.4.6)
Installing collected packages: py, pluggy, packaging, iniconfig, pytest
Successfully installed iniconfig-1.1.1 packaging-21.3 pluggy-1.0.0 py-1.11.0 pytest-6.2.5
$ 
```
Now it works!
```
$ make pytest
pytest codespell_lib
======================================================= test session starts ========================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /my/path/codespell, configfile: setup.cfg
[...]
```
Looks like a pytest bug, doesn't it?

**Comment by peternewman** [comment]
> About the first question, I had missed the answer in the [README](https://github.com/codespell-project/codespell/blob/master/README.rst). I was looking under the wrong paragraph, [Requirements](https://github.com/codespell-project/codespell/blob/master/README.rst#requirements) instead of [Development Setup](https://github.com/codespell-project/codespell/blob/master/README.rst#development-setup):

My gut feeling is that documentation is in the right place, as your average user just wants to know what they need to use it, but we could always signpost the dev section from the main requirements bit.

> Looks like a pytest bug, doesn't it?

Yeah, probably. My guesses would be one or more of the following:

- Core versus extension version mismatch
- Python path issue
- Pytest bug

**Comment by DimitriPapadopoulos** [comment]
Yes, it might be version mismatch: 4.6.9 and 6.2.5 are far apart. But then shouldn't `pip` get a version of `pytest-cov` that matches that of `pytest`? Unless `pytest` does not instruct `pip` to do the right thing – either in current version or in the past 4.6.9 version. I cannot tell, I don't know enough about `pip` internals.

I'm closing this, I just thought I should make a note of it in case other users have the same problem.
