### ISSUE TITLE
LOD (Level Of Detail) should not be treated as an error

### ISSUE THREAD

**Issue by matkoniecz** [codespell-project/codespell#2256]

**Comment by peternewman** [comment]
:laughing: is od->of present already.

Feel free to open a PR to move it to rare or maybe code would be better, but it feels fairly niche compared to load.

**Comment by peternewman** [comment]
> laughing is od->of present already.

It is:
https://github.com/codespell-project/codespell/blob/e63fa1204f11be62fa9697be7fc58305388c0826/codespell_lib/data/dictionary_code.txt#L36
