### ISSUE TITLE
'Stringly typed' corrected to 'strongly typed'

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [codespell-project/codespell#2260]
Our resident typo fixer didn't notice 'stringly typed' was intentional: https://git.libreoffice.org/core/commit/06dbd2f50662d04d03140458afdff4501ea5827e

I guess it would make sense to teach codespell about it.

**Comment by peternewman** [comment]
Agreed it seems to have a fairly broad usage, feel free to open a PR moving stringly->strongly into the code dictionary so people can avoid it for codebases.

**Comment by ilmari-lauhakangas** [comment]
Sorry for the noise, I did not test this myself and it seems the fix was done manually. So there is nothing to change in codespell.

**Comment by peternewman** [comment]
I thought I'd checked the dictionary, but clearly not, I've added it to the code dictionary in #2268 as it's clearly a potential typo.

**Comment by ilmari-lauhakangas** [comment]
> I thought I'd checked the dictionary, but clearly not, I've added it to the code dictionary in #2268 as it's clearly a potential typo.

Sorry, but this is the opposite of what I want :( Stringly typed is **not** a typo: https://smartflow.wordpress.com/2015/04/20/code-smell-stringly-typed/

Codespell is fine as it is, the mistaken assumption was made by the person using codespell. Please don't add stringly->strongly to codespell!

**Comment by peternewman** [comment]
No it's not, trust me. Firstly stringly didn't exist in codespell at all (likewise codespell wouldn't catch the double is, so I think both fixes there were human eyeballs or another tool.

Despite the possibly confusing name, our code dictionary is disabled by default and for words which are valid in code, like e.g. `stoll->still` so the idea is you'd only run it on say documentation, or stuff that wasn't code at all. In those contexts, stringly is likely to be a typo.
