### ISSUE TITLE
Remove 'sur' from dictionary (due to macOS 'Big sur' release name)

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#2299]
Too many false positives from this. I vote to remove or put in to a dictionary that doesn't get referenced by default

**Comment by peternewman** [comment]
Well code would be the obvious one to move it to...

**Comment by luzpaz** [comment]
It doesn't really fit the description, right?

```
'code' for words from code and/or mathematics that are likely to be typos in other contexts
```

**Comment by peternewman** [comment]
It doesn't seem a huge leap, code/computing. If your spellchecking a cookery book for example, it's likely to be an error if it appears!

**Comment by peternewman** [comment]
Thanks @luzpaz . To be clear I'm not against creating a new dictionary if we can work out a sensible demarcation, but given it only wants skipping in some contexts, I don't feel removing it entirely is the way to go (and we currently have no way to stop it being re-added in that case either...).

**Comment by henryiii** [comment]
Is there any way to make "sur" be a typo but "Sur" not be? I've had issues before trying to use capital letters in the ignore list - "sur" is still very likely to be a typo.
