### ISSUE TITLE
Remove ` interruptable->interruptible`

### ISSUE THREAD

**Issue by janosh** [codespell-project/codespell#2301]
I vote to remove `interruptable->interruptible` and `uninterruptable->uninterruptible`:

https://github.com/codespell-project/codespell/blob/3c93ad6d70f543f79b394da074047887bfa765a3/codespell_lib/data/dictionary.txt#L17986

[All dictionaries](https://en.wiktionary.org/wiki/interruptable) I've consulted state these as equivalent.

**Comment by peternewman** [comment]
Do you have a link to a more formal dictionary (Oxford/Cambridge/Something US based or whatever) which says that -able is acceptable?

**Comment by janosh** [comment]
Looks like Cambridge dict [doesn't have interruptible _or_ interruptable](https://dictionary.cambridge.org/spellcheck/english/?q=interruptible).

Oxford dict also says [both forms are accepted](https://www.oed.com/view/Entry/98277?redirectedFrom=interruptible#eid).

<img src="https://user-images.githubusercontent.com/30958850/156619759-aba96ad4-13cc-40b9-afa3-60a90814d79d.png" alt="OED" width=300>

**Comment by janosh** [comment]
@peternewman Is the OED reference sufficient for merging #2305?

**Comment by DimitriPapadopoulos** [comment]
Collins only has [interruptible](https://www.collinsdictionary.com/dictionary/english/interrupt).
Merriam-Webster only has [interruptible](https://www.merriam-webster.com/dictionary/interruptible).
Dictionary.com only has [interruptible](https://www.dictionary.com/browse/interrupt).

Google has 81 000 hits for [interruptable](https://www.google.com/search?q=interruptable) and 1 350 000 for [interruptible](https://www.google.com/search?q=interruptible).

But yes, Oxford and other sources such as [Wiktionary](https://en.wiktionary.org/wiki/interruptable) do find both forms acceptable.

**Comment by skangas** [comment]
I'd suggest closing this issue based on the above discussion.

**Comment by kurtmckee** [comment]
@larsoner I think this issue can be closed. PR #2305 was closed but this issue was left open.
