### ISSUE TITLE
Consider adding `ploted ==> plotted` to dictionary

### ISSUE THREAD

**Issue by matthewfeickert** [codespell-project/codespell#2340]
Hi. :wave: As noticed in https://github.com/matplotlib/matplotlib/pull/22777#issuecomment-1116954036 `codespell` `v2.1.0` doesn't catch `ploted` as being a typo of `plotted`. Would you consider a PR that adds

```
ploted->plotted
``` 

to one of the dictionaries (probably [`codespell_lib/data/dictionary.txt`](https://github.com/codespell-project/codespell/blob/2a6f7752ceeff8e9db05e06f5057a2b878e46ff9/codespell_lib/data/dictionary.txt))?

**Comment by luzpaz** [comment]
Feel free to submit a PR for this

**Comment by matthewfeickert** [comment]
@luzpaz will do. :+1: In the future, what's the dev team's preferred way of iterating on questions like this: to have people open up Issues for each addition, or to have people just open PRs if the changes seem "uncontroversial" and then close them if the dev team think the changes don't benefit the project?

**Comment by peternewman** [comment]
> @luzpaz will do. 👍 In the future, what's the dev team's preferred way of iterating on questions like this: to have people open up Issues for each addition, or to have people just open PRs if the changes seem "uncontroversial" and then close them if the dev team think the changes don't benefit the project?

Hi @matthewfeickert ,

Yeah just go straight for a PR, and feel free to put a few changes together in one PR if you'd like, although more than about 20 often gets a bit unwieldy with finding issues on some bits and them blocking others.

I wouldn't generally bother with an issue about a single entry, but perhaps about a more general thing say, or a lot of bulk changes. Or I suppose anything that involves a lot of work to generate the PR for and could potentially be controversial (say adding plurals for everything that's missing them), just in case it got rejected so the work wasn't wasted. Although equally you could open a sample PR with a few for an initial review.

But generally just go straight for a PR if it's just a dictionary change!
