### ISSUE TITLE
New Release Request

### ISSUE THREAD

**Issue by clickthisnick** [codespell-project/codespell#2366]
Hello, just wondering, the last tagged release was June 10, 2021. 

I noticed someone else posted an issue asking for a new release before. 

Could we get a new release, there are a lot of typos added that would be useful. Thanks!

**Comment by sylvestre** [comment]
Indeed, it would be nice. cc @luzpaz if you could help :)

**Comment by luzpaz** [comment]
@peternewman any open PRs we should address before release?

**Comment by luzpaz** [comment]
bump

**Comment by sylvestre** [comment]
@luzpaz Maybe just go ahead? It would be nice to have a more recent version for the next Debian stable release

**Comment by luzpaz** [comment]
@sylvestre when is the cut-off date ?

**Comment by luzpaz** [comment]
@larsoner do you mind helping cut a new release?

**Comment by sylvestre** [comment]
still a few months :)

**Comment by larsoner** [comment]
https://github.com/codespell-project/codespell/releases

pushed to PyPi, just need https://github.com/conda-forge/codespell-feedstock/pull/6 for conda-forge
