### ISSUE TITLE
dictionary: 'namesapce'

### ISSUE THREAD

**Issue by penguin42** [codespell-project/codespell#2387]
I'm noticing 'namesapce' is a very common typo in a few projects; it's probably worth adding it to the dictionary.

**Comment by peternewman** [comment]
Good spot @penguin42 . Feel free to just open a Pull Request directly to add it, you don't need to bother raising an issue first.

**Comment by penguin42** [comment]
Thanks; https://github.com/codespell-project/codespell/pull/2388

**Comment by luzpaz** [comment]
Closed by [cfe751a](https://github.com/codespell-project/codespell/commit/cfe751aedb234e262d7e32c1d568939c2ccd4e36)
