### ISSUE TITLE
Codespell doesn't identify issues in docstrings and markdown

### ISSUE THREAD

**Issue by Goldziher** [codespell-project/codespell#2411]
Hi there,

So I am running codespell using pre-commit and it doesn't identify errors inside docstrings and markdown files. See for example this commit in Starlite --> https://github.com/starlite-api/starlite/pull/283/commits/26afa44cb8e044eda0f9440da5d5cc9d37e2ef09, I fixed typos in it using intellij code inspection, all of which were not identified by codespell at all.

**Comment by peternewman** [comment]
`Respose` and `arbitary` are present in the main codespell dictionary (I didn't double-check the others). But I think the backticks around it are possibly excluding it at being a standalone word, probably likewise the underscore after the arbitrary typo, it depends on the regex.

Feel free to submit further typos to the dictionary as a PR, but I suspect you shouldn't just steal what intellij found...

**Comment by Goldziher** [comment]
> `Respose` and `arbitary` are present in the main codespell dictionary (I didn't double-check the others). But I think the backticks around it are possibly excluding it at being a standalone word, probably likewise the underscore after the arbitrary typo, it depends on the regex.
> 
> Feel free to submit further typos to the dictionary as a PR, but I suspect you shouldn't just steal what intellij found...

Issue is not about dictionary words, it's about typos not being identified in various places. This indicates a parsing bug imo.

**Comment by peternewman** [comment]
The regex can be customised on the command line, PRs welcome for one that improves on this. I think there was one to handle snake case for your arbitrary example.

**Comment by aastashov** [comment]
I encountered the same problem, but as it turns out, it's not a problem. Your regex works as it should. The problem turned out to be in the dictionary.

I'll attach a code example and the result of the test.

some.py
```python
# tpyo error
def some_function():
    """dcuments test"""
    ...
```

```bash
codespell some.py
some.py:1: tpyo ==> typo
some.py:3: dcuments ==> documents
```

You can supplement the dictionaries with your own words where there was a typo.
https://github.com/codespell-project/codespell/tree/master/codespell_lib/data

Thanks for your library!
