### ISSUE TITLE
Suggestions for Removal

### ISSUE THREAD

**Issue by kianmeng** [codespell-project/codespell#2444]
`accreting->accrediting` -> https://www.merriam-webster.com/dictionary/accreting
`falsy->falsely, false,` -> https://developer.mozilla.org/en-US/docs/Glossary/Falsy

**Comment by janosh** [comment]
I agree `falsy` should not be flagged.

**Comment by peternewman** [comment]
Please feel free to open a PR moving falsy to the code dictionary, but it's not a proper word despite what Mozilla may say!

Accreting should be moved into rare given it is a real word, albeit a generally unlikely one.
