### ISSUE TITLE
How to ignore certain words in codespell

### ISSUE THREAD

**Issue by vineetsharma883** [codespell-project/codespell#2450]
I am using codespell as pre-commit hook, which points out `IST` as spelling error. How do I ignore latter word ?

**Comment by vineetsharma883** [comment]
I tried by adding with following config in `.codespellrc`

```
[codespell]
ignore-words=ignore_words.txt
```

where `ignore_words.txt` has following 
```
IST
```

But this does not work

**Comment by peternewman** [comment]
Did you read our usage doc:
https://github.com/codespell-project/codespell#usage

Specifically:

> Important note: The list passed to -I is case-sensitive based on how it is listed in the codespell dictionaries.
