### ISSUE TITLE
Issue with --ignore-words?

### ISSUE THREAD

**Issue by jeeftor** [codespell-project/codespell#2451]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/6491743/184672135-cea3a3b9-7444-49cd-88d9-320e91ea60bb.png">

I feel like things aren't working as they should

<img width="350" alt="image" src="https://user-images.githubusercontent.com/6491743/184672186-9f621440-63cf-466c-9bed-11f63816e47c.png">

**Comment by peternewman** [comment]
Did you read our usage doc:
https://github.com/codespell-project/codespell#usage

Specifically:

> Important note: The list passed to -I is case-sensitive based on how it is listed in the codespell dictionaries.

**Comment by jeeftor** [comment]
Um. They are all the same case???

**Comment by peternewman** [comment]
> I previously left #2451 which was closed however I feel this was done incorrectly.
> 
> My ignore list was:
> 
> ### ignore.txt
> ```
> FRO
> THA
> ND
> SUR
> ```
> 
> My file I was spell checking was:
> 
> ### in.txt
> ```
> FRO FRUM FROM
> ND NORTH SOUTH
> ```
> 
> And the output of CodeSpell is:
> 
> `codespell --ignore-words=ignore.txt in.txt`
> 
> ```
> in.txt:1: FRO ==> FOR, FROM
> in.txt:2: ND ==> AND, 2ND
> ```
> 
> As per the docs the spelling **IS** case sensitive... so am I missing something here?
> 
> `FRO` is in the ignore list - and as such shouldn't `FRO` in the input file not be flagged as an issue?

Grep dictionary.txt and you'll find fro is in lower case in our dictionary. Some clever magic makes it show as upper case because your input string is upper case.

**Comment by jeeftor** [comment]
If I understand correctly:

I put `FRO` in my ignore list... and I put `FRO` in my text but the built in `fro` (lowercase) is being flagged?

**Comment by peternewman** [comment]
Yes, put fro in your ignore list (as per the docs) and it should work as you intended.

**Comment by andyholmes** [comment]
Seems like a good way to close this would be a README.md update including such an example.

I think it's not obvious that *"case-sensitive based on how it is listed in the codespell dictionaries"*, means that your ignore match is case-sensitive, while the dictionary match itself is case-insensitive.

**Comment by peternewman** [comment]
> Seems like a good way to close this would be a README.md update including such an example.

Do you mean "so if you want to ignore FRO, you'll need to add fro to your ignore list, because the codespell dictionaries feature the correction `fro->for`? 

> I think it's not obvious that _"case-sensitive based on how it is listed in the codespell dictionaries"_, means that your ignore match is case-sensitive, while the dictionary match itself is case-insensitive.

Pull requests or comments welcome for how to make that more obvious.

I must admit it's been a while since I've personally looked at that bit of code for why we don't just lower-case the ignore list but I suspect it might be to allow potential future features such as correcting javascript to JavaScript based on a case specific dictionary.

Would a warning/info notification that "you've ignored FRO; it doesn't exist in the dictionary but fro does" be useful?

**Comment by andyholmes** [comment]
Took a stab at updating the README in #2466.

> Would a warning/info notification that "you've ignored FRO; it doesn't exist in the dictionary but fro does" be useful?

I think a warning might be a good idea, I expect that's the place people will look first anyways.

**Comment by mreidel-godaddy** [comment]
@peternewman I just fell for the same issue: flagged was `hasTable->hashable`, I put `hasTable` in the ignore list, but it should have been `hastable`.

> Would a warning/info notification that "you've ignored FRO; it doesn't exist in the dictionary but fro does" be useful?

That would have been very helpful indeed!

**Comment by giswqs** [comment]
The `--ignore-words-list` option seems to have no effect. The two words included in the ignored words list are still being flagged as typos. Anyone knows why?

![image](https://user-images.githubusercontent.com/5016453/194217753-734f677f-b4e6-4052-8d08-9aacdd30160c.png)

https://github.com/nasa/Transform-to-Open-Science/pull/275

**Comment by luckman212** [comment]
What if I ***want*** `aCount` to be allowed/ignored but I want `acount` to be flagged as a misspelling? Impossible?

**Comment by peternewman** [comment]
> What if I _**want**_ `aCount` to be allowed/ignored but I want `acount` to be flagged as a misspelling? Impossible?

The ignore words are about skipping entries that are normally in our dictionary, so you can't skip a typo from the dictionary (ACOUNT) and expect some variants of it to be flagged and others to be ignored.

While I can see the benefit of this use case, I think it would be confusing for the majority of people where they want to skip a word as it's a special term in their particular domain for example.

I think two things would fix your use case, in the short term, using the ignore regex option to essentially vanish aCount from the source text codespell is checking, alternatively when we add camel-case support, that will fix it properly, with the benefit of also flagging aCont as a typo too (potentially)!

**Comment by Sopor** [comment]
I'm new to codespell, so maybe i do something wrong here, so please bear with me 😊

I wanted to ignore the word `clientA`
`chain\client.lua:12: clientA ==> client`

I created a config file and added
`ignore-words-list = clientA`
to ignore `clientA`, but it didn't worked.

Readme file:
`Important note: The list passed to -I is case-sensitive based on how it is listed in the codespell dictionaries.`

When i changed the `clientA` to `clienta` it worked.

Shouldn't i use the same case as the word i want to ignore?

**Comment by andyholmes** [comment]
No, that's what this issue is about clarifying. This is my current proposed change to the README:


Ignoring Words
--------------

When ignoring false positives, note that spelling errors are *case-insensitive* but words to ignore are *case-sensitive*. For example, the dictionary entry ``wrod`` will also match the typo ``Wrod``, but to ignore it you must pass ``wrod``.

The words to ignore can be passed in two ways:

1. ``-I``: A file with a word per line to ignore::

        codespell -I FILE, --ignore-words=FILE

2. ``-L``: A comma separated list of words to ignore on the command line::

        codespell -L word1,word2,word3,word4

**Comment by prestoncarman** [comment]
Ignoring words has been a confusing part of codespell for me. @andyholmes I like your explanation on how the ignore feature works.

After reading this threaded, I realize that the ignore list is not for the text or word in my source code, but for the codespell dictionary. This makes more sense as to why it must be lowercase.

I think adding the warning and clearing up the description in the README (using @andyholmes description above) would be helpful to new (and current) users of codespell.
