### ISSUE TITLE
Issue with --ignore-words

### ISSUE THREAD

**Issue by jeeftor** [codespell-project/codespell#2452]
I previously left #2451 which was closed however I feel this was done incorrectly.

My ignore list was:

### ignore.txt
```
FRO
THA
ND
SUR
```

My file I was spell checking was:

### in.txt
```
FRO FRUM FROM
ND NORTH SOUTH
```

And the output of CodeSpell is:

`codespell --ignore-words=ignore.txt in.txt`

```
in.txt:1: FRO ==> FOR, FROM
in.txt:2: ND ==> AND, 2ND
```

As per the docs the spelling **IS** case sensitive... so am I missing something here?

`FRO` is in the ignore list - and as such shouldn't `FRO` in the input file not be flagged as an issue?

**Comment by peternewman** [comment]
Please don't open a new issue, generally people aren't adverse to re-opening an issue if further clarity is required. I've replied on the old one so it's all there for other people.
