### ISSUE TITLE
codespell 2.2.0 will not ignore the word 'Jupyter'

### ISSUE THREAD

**Issue by ajslater** [codespell-project/codespell#2458]
codespell 2.1.0 works

codespell 2.2.0 includes a couple more words i needed to ignore, which all look like good ones to check for.
However, codespell 2.2.0 cannot ignore the word 'Jupyter' if specified in setup.cfg, or with the `-L` command line argument. In my case this word appears in my .gitignore and codespell even flags the word in my setup.cfg under the codespell block where i was trying to ignore it.

**Comment by peternewman** [comment]
As per #2451 and others, you'll need to ignore it as `jupyter`. Are you checking documentation though if you're using the code dictionary?
