### ISSUE TITLE
Add type hints and py.typed marker

### ISSUE THREAD

**Issue by kkirsche** [codespell-project/codespell#2465]
I'm willing to contribute this if it is of interest, but want to ensure it'd be accepted before doing the leg work.

This issue is asking if it would be acceptable to add Python type hints to the codespell project. Type hints were introduced in [PEP 484](https://peps.python.org/pep-0484/) with type information described on:
https://docs.python.org/3/library/typing.html

Typing features are backported to older releases via https://pypi.org/project/typing-extensions/

Type hints allow for static verification that the code will work based on the provided type information. The `py.typed` marker is used to indicate to users that this package contains type hints that are allowed to be used in other projects, such as programmatic automation which uses this library. The `py.typed` marker is explained in [PEP 561](https://peps.python.org/pep-0561/)

Please let me know if you have any questions

**Comment by jdufresne** [comment]
Type hints were added in https://github.com/codespell-project/codespell/commit/8d0d82bcc07aaef5211127683aba7de67b923aac. This issue can be closed.
