### ISSUE TITLE
Suggestion to remove `ore->or`

### ISSUE THREAD

**Issue by janosh** [codespell-project/codespell#2510]
Example false positive:

> Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal with properties that are intermediate between those of its periodic table column-adjacent chalcogen elements sulfur and tellurium. It rarely occurs in its elemental state in nature, or as pure >**ore**< compounds.

**Comment by luzpaz** [comment]
I still see this typo though from time to time.

**Comment by janosh** [comment]
Feel free to close if the true positives outweigh the false positives in your opinion. I can always ignore that word on a project-by-project basis.

**Comment by peternewman** [comment]
Yeah it's already in rare @janosh , so you can either turn that off for true typos only, or ignore just that one word as appropriate.
