### ISSUE TITLE
pyproject.toml config not supported?

### ISSUE THREAD

**Issue by banesullivan** [codespell-project/codespell#2522]
The README states:

> Codespell will also check in the current directory for a pyproject.toml (or a path can be specified via --toml <filename>) file, and the [tool.codespell] entry will be used as long as the [tomli](https://pypi.org/project/tomli/) package is installed, for example

However, I have been unable to get this to work in both https://github.com/pyvista/pyvista/pull/3328/ and in this standalone repository: https://github.com/banesullivan/codespell-pyproject-issue

The `tomli` package is installed yet `codespell` does not pick up on the `pyproject.toml` configuration.

You can see this erroring in https://github.com/banesullivan/codespell-pyproject-issue/actions/runs/3230877580/jobs/5289808823#step:5:12 where the `ignored.txt` file should have been ignored by the config in `pyrpoject.toml`

Any ideas what I'm doing wrong here?

**Comment by peternewman** [comment]
> Any ideas what I'm doing wrong here?

Just being impatient! 😄 

As you'll see from my PR it works fine if you either install from git, or will do if you wait for a new release:
https://github.com/peternewman/codespell-pyproject-issue/actions/runs/3231297840/jobs/5290670231

**Comment by banesullivan** [comment]
welp 🤦‍♂️ I did not realize this was a pre-release feature. Any idea when the next release might land?

Thanks!

**Comment by peternewman** [comment]
@larsoner normally does those because I'm terrible at actually doing it! 😄

**Comment by larsoner** [comment]
After a little bit of iteration in `master` and cutting https://github.com/codespell-project/codespell/releases/tag/v2.2.2, we have https://pypi.org/project/codespell/2.2.2/#files

**Comment by banesullivan** [comment]
Thank you!!
