### ISSUE TITLE
Consider re-adding "shouldnot" to allow dictionary

### ISSUE THREAD

**Issue by jackfrancis** [codespell-project/codespell#2528]
Hi folks,

It seems that w/ today's v2.2.2 release the word "shouldnot" has been demoted to "not allowed by default". Because terms like `Should` and `ShouldNot` are rather common in test assertion libraries across the developer ecosystem, I wonder if other folks had to quickly update their ignore files today to unblock CI.

Here's one example of some usages in the golang ginkgo test framework:

- https://pkg.go.dev/github.com/onsi/gomega#AsyncAssertion

Thanks for consideration!

**Comment by jackfrancis** [comment]
Thank you @DimitriPapadopoulos !

**Comment by DimitriPapadopoulos** [comment]
You're welcome and thank you for this contribution.
