### ISSUE TITLE
Report when we're using setup.cfg, .codespellrc, pyproject.toml etc

### ISSUE THREAD

**Issue by sappelhoff** [codespell-project/codespell#2534]
identified in https://github.com/bids-standard/bids-specification/pull/1322#issuecomment-1280914648

How to reproduce:

- run a basic codespell GH action (without passing `with:` arguments)
- add a `.codespellrc` configuration file to the repo root
- the config file **is** being observed BUT
- the "argument summary" in the GH actions log is not reflecting that

![image](https://user-images.githubusercontent.com/9084751/196197800-7c5be6d3-6204-4535-83cd-4eb0db93ce2f.png)

**Comment by peternewman** [comment]
I've moved this to the main codespell repo now and tweaked the title given it's not directly action specific.
