### ISSUE TITLE
 Welcome to Hacktoberfest!/Looking for a good first issue?

### ISSUE THREAD

**Issue by peternewman** [codespell-project/codespell#2536]
Happy Hacktober! :ghost:

If you'd like to participate in Hacktoberfest via Codespell then have a look at some of our sets of issues here:
https://github.com/codespell-project/codespell/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+

We've decided we'll only tag code related pull requests as hacktoberfest-accepted, rather than dictionary ones, as they generally need more meaningful input.

If you haven't already, sign up for Hacktoberfest here - https://hacktoberfest.digitalocean.com/
:shirt: Make 4 pull requests during the month of October and you will receive a free t-shirt (or you have the option to plant a tree if you already have enough t-shirts )

**Comment by Premjeet1804** [comment]
!assign me please

**Comment by kurtmckee** [comment]
@larsoner, @peternewman this issue can be closed.

**Comment by peternewman** [comment]
> @larsoner, @peternewman this issue can be closed.

How come @kurtmckee ? It's still a good intro to places to start, and I'd imagine Hacktoberfest will happen again this year (unless you know otherwise)?

**Comment by kurtmckee** [comment]
I was briefly triaging issues; this issue isn't actionable and has no closure conditions other than that Hacktoberfest 2022 has ended. It could live on in a CONTRIBUTING doc in the root of the repo, though.

**Comment by luzpaz** [comment]
I defer to you @peternewman

**Comment by DimitriPapadopoulos** [comment]
There will be a **Hacktoberfest 2023**: https://www.works.so/blog/developers/hacktoberfest-2023-a-complete-guide

@larsoner You would need to remove the [hacktoberfest2022](https://github.com/topics/hacktoberfest2022) tag and add the [hacktoberfest2023](https://github.com/topics/hacktoberfest2023) one:
![hacktoberfest2022](https://github.com/codespell-project/codespell/assets/3234522/6a8cf922-a43b-409b-b8c1-a6606b9f14d0)

**Comment by larsoner** [comment]
Done!
