### ISSUE TITLE
`make check-distutils`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2599]
Target `check-distutils` in the `Makefile` had not been changed during the `pyproject.toml` migration (#2523):
https://github.com/codespell-project/codespell/blob/1302d7974fb12ae2d723376e81e9b2f1e5c7a5bd/Makefile#L50-L51

It is broken:
```
$ make check-distutils 
python setup.py check --restructuredtext --strict
running check
warning: check: missing required meta-data: name, version, url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

error: Please correct your package.
Makefile:51: recipe for target 'check-distutils' failed
make: *** [check-distutils] Error 1
$ 
```
We probably want to move away from `setup.py check` anyway. The alternative appears to be `twine check`, at least according to [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

**Comment by jdufresne** [comment]
The move to `twine check` was done in ba4e71d9ecc0b48946daac92430d73e57703c0b4. I believe this issue can be closed.
