### ISSUE TITLE
Using codespell as a library

### ISSUE THREAD

**Issue by pawamoy** [codespell-project/codespell#2607]
Hello, thanks for this great project!

I'm trying to integrate it in a MkDocs plugin that spellchecks docs pages.
Is there a guide or small snippets somewhere that show how we could use codespell as a Python library rather than a CLI?

This is what I have so far:

```python
"""Backend for the `codespell` tool.

Testing adn stuf.
"""

from __future__ import annotations

import os
from typing import Any

# importing private variables from private module, not great
from codespell_lib._codespell import (
    Misspelling,
    _builtin_default,
    _builtin_dictionaries,
    _data_root,
    build_dict,
    fix_case,
)
from mkdocs.structure.pages import Page

from mkdocs_spellcheck.backends import Backend
from mkdocs_spellcheck.loggers import get_logger

logger = get_logger(__name__)

DEFAULT_DICTS = _builtin_default.split(",")


class CodespellBackend(Backend):
    def __init__(self, config: dict[str, Any], known_words: set[str] = None) -> None:
        known_words = known_words or set()
        use_dictionaries = []
        for dictionary in config.get("dictionaries", DEFAULT_DICTS):
            for builtin in _builtin_dictionaries:
                if builtin[0] == dictionary:
                    use_dictionaries.append(os.path.join(_data_root, f"dictionary{builtin[2]}.txt"))
        self.misspellings: dict[str, Misspelling] = {}
        for dictionary in use_dictionaries:
            build_dict(dictionary, self.misspellings, known_words)

    def check(self, page: Page, word: str) -> None:
        if word in self.misspellings:
            # reason = self.misspellings[word].reason
            fixword = fix_case(word, self.misspellings[word].data)
            logger.warning(f"(codespell) {page.file.src_path}: Misspelled '{word}', did you mean '{fixword}'?")
```

This simple integration works fine:

```console
% python -m mkdocs build -s
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/pawamoy/data/dev/mkdocs-spellcheck/site
WARNING  -  mkdocs_spellcheck: (codespell) reference/mkdocs_spellcheck/backends/codespell.md: Misspelled 'adn',
            did you mean 'and'?
```

I fear I will have to copy/paste more and more logic from `_codespell.py` into my backend `__init__` and `check` methods if I want to support more options from Codespell :thinking:

**Comment by pawamoy** [comment]
You are right, I'm actually splitting words from big HTML strings myself (well, using a proper HTML parser), and then calling a function on each word.

Arguably, writers/devs should probably call codespell themselves on their sources (both markdown pages and Python source files): that would work better. But MkDocs is language agnostic, and many writers use it through Docker, so the "Python stack" can be hidden for a lot of them, and so they probably would not install Python and codespell locally. My plugin kinda fixes it for them. That's the reason why I'm integrating codespell in the plugin :slightly_smiling_face: (I'm also having fun implementing several spellcheck backends into the plugin!)

Anyway, my snippet above works fine. If you ever decide to refactor things a bit to expose more of the logic in a publicly supported manner, and less tied to the CLI, that would be awesome! I won't open a feature request for this, that would feel too entitled :sweat_smile: I'll close this issue now :slightly_smiling_face: 

Thank you very much for your time, help, and again for this very nice project!

**Comment by peternewman** [comment]
> Arguably, writers/devs should probably call codespell themselves on their sources (both markdown pages and Python source files): that would work better.

Yes definitely if they're generating pages from Markdown/Python. Are you just auto-fixing then (which is risky) or if you're doing it manually the fixes won't get back into the source documents "upstream".

> Anyway, my snippet above works fine. If you ever decide to refactor things a bit to expose more of the logic in a publicly supported manner, and less tied to the CLI, that would be awesome!

Glad to hear it, I think that's a very fair request, and similar to #2138 , I think they are just two different ways of looking at/solving the issue, do you add the context aware filter to codespell, or add codespell as a library to the existing tool. They'll both have benefits and disadvantages.

> I won't open a feature request for this, that would feel too entitled 😅 I'll close this issue now 🙂

I don't think so, as above, I think it's valid, I think the reason to close it is because it duplicates the other issue logically at least, if not the exact context.

**Comment by pawamoy** [comment]
The plugin just warns about incorrect spelling, it does not (auto)fix anything.

If you think it could be useful to have a dedicated ticket for making codespell more "library friendly", I can open one, and we'll be able to reference both this issue and #2138 in it; just let me know. I just feel like this hasn't been asked enough times to warrant an explicit request for it.
