### ISSUE TITLE
New option to run on individual files

### ISSUE THREAD

**Issue by waldyrious** [codespell-project/codespell#2622]
I'd like to be able to run codespell on one or more specific files, rather than an entire directory. This would essentially have the opposite effect of `-S`/`--skip`.

The option should support filenames, directories, and blob patterns, all three as both a single argument and comma-separated lists. For example, if the option name is `-f`/`--files`:

```
codespell -f foobar.txt
```

```
codespell --files="foo.txt,bar.txt"
```

```
codespell --files="./some/folder"
```

```
codespell --files="*.md,*.txt"
```

**Comment by DimitriPapadopoulos** [comment]
The executable already accepts file as arguments:
```
usage: codespell [-h] [--version] [-d] [-c] [-w] [-D DICTIONARY] [--builtin BUILTIN-LIST] [--ignore-regex IGNORE_REGEX] [-I FILE]
                 [-L WORDS] [--uri-ignore-words-list WORDS] [-r REGEX] [--uri-regex URI_REGEX] [-s] [--count] [-S SKIP] [-x FILE]
                 [-i INTERACTIVE] [-q QUIET_LEVEL] [-e] [-f] [-H] [-A LINES] [-B LINES] [-C LINES] [--config CONFIG] [--toml TOML]
                 [files ...]
```

**Comment by waldyrious** [comment]
Oh, I totally missed that. I suppose we might want to make this more evident in the documentation 🤔

**Comment by DimitriPapadopoulos** [comment]
It didn't strike me when I started using codespell, because I expect all commands that operate on files to accept files as arguments. But I have to agree this doesn't appear in [README.srt](https://github.com/codespell-project/codespell/blob/master/README.rst).
