### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by skangas** [codespell-project/codespell#2644]
The current master branch contains an important fix from the point of view of Emacs Lisp (see #2609 and #2378). It would be useful to get that fix released, as that bug is almost a show-stopper for using codespell in Emacs and related packages. Could you please consider releasing a new version 2.2.3?

Thanks.

**Comment by neiljp** [comment]
I agree this would be useful to have available, since while #2713/#2715 is merged, no release means use of pyproject.toml configuration on python 3.11 fails with no warning.

**Comment by larsoner** [comment]
Done in https://github.com/codespell-project/codespell/releases/tag/v2.2.3 and out on PyPI as https://pypi.org/project/codespell/2.2.3/
