### ISSUE TITLE
Add `donut`, and other words missing from aspell

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2657]
```
doughnut->donut
doughnuts->donuts
```
Unfortunately, `donut` is missing from the _aspell_ dictionary.
Until it is added to _aspell_ or we modify our CI tests, we cannot add it.

See #2574 and https://github.com/GNUAspell/aspell/issues/628.

**Comment by skangas** [comment]
I'm adding in these too, that also seem to be missing from the _aspell_ dictionary:
```
aesthetic->esthetic
aesthetically->esthetically
aesthetics->esthetics
```

**Comment by DimitriPapadopoulos** [comment]
May be fixed by https://github.com/codespell-project/codespell/pull/1485.

**Comment by DimitriPapadopoulos** [comment]
See also #1480, #1562, #103, ...
