### ISSUE TITLE
ignore-words-list doesn't work properly?

### ISSUE THREAD

**Issue by makselll** [codespell-project/codespell#2662]
Why does it give me the error?

I've tested those cases:
`print('fo')`
`print('Autor')`

My .pre-commit-config.yaml
<img width="564" alt="image" src="https://user-images.githubusercontent.com/26189979/209552773-9c4f9fda-efb0-47b5-be1b-51554a4ff99b.png">

My pyproject.toml
<img width="478" alt="image" src="https://user-images.githubusercontent.com/26189979/209552738-f000b900-5860-4720-85ef-f3f6b133c28d.png">

The result is error - Autor ==> Author
But 'fo' was ignored 

How can I ignore the 'Autor' word?

**Comment by DimitriPapadopoulos** [comment]
Change `Autor` to `autor`

See

**Comment by makselll** [comment]
> Change `Autor` to `autor`.
> 
> See [`README.rst`](https://github.com/codespell-project/codespell/blob/master/README.rst#usage):
> 
> > **Important note:** The list passed to `-L` is case-sensitive based on how it is listed in the codespell dictionaries.

No, It didn't help 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/26189979/209663963-796871fc-369b-41b4-b196-bdd625d277bb.png">

**Comment by DimitriPapadopoulos** [comment]
It works for me with codespell 2.2.2 from the command line:
```sh
$ cat > constant.py
Autor
$ 
$ codespell ./constant.py
./constant.py:1: Autor ==> Author
$ 
$ codespell -L autor ./constant.py
$ 
$ cat > pyproject.toml
[tool.codespell]
ignore-words-list = "autor"
$ 
$ codespell --toml pyproject.toml ./constant.py
$ 
```
Please check whether works for you too from the command line too.
