### ISSUE TITLE
"sharable" false positive?

### ISSUE THREAD

**Issue by polluks2** [codespell-project/codespell#2690]
See https://grammarist.com/spelling/sharable-shareable/

**Comment by DimitriPapadopoulos** [comment]
Indeed, both variants can be found in:
* [Cambridge](https://dictionary.cambridge.org/dictionary/english/shareable)
* [Merriam-Webster](https://www.merriam-webster.com/dictionary/sharable)
* [Collins](https://www.collinsdictionary.com/dictionary/english/share)
* [Wordsmyth](https://www.wordsmyth.net/?ent=share)
* [Dictionary.com](https://www.dictionary.com/browse/share)

A single dictionary has `shareable` only:
* [Macmillan](https://www.macmillandictionary.com/dictionary/american/shareable)

Some dictionaries lack both:
* [Oxford Learner's](https://www.oxfordlearnersdictionaries.com/definition/english/share_1)
* [Longman](https://www.ldoceonline.com/dictionary/share)
* [Chambers](https://chambers.co.uk/search/?query=share&title=21st)

Google:
* `shareable` [276,000,000 hits](https://www.google.com/search?q=shareable)
* `sharable` [12,500,000 hits](https://www.google.com/search?q=sharable)

**Comment by skangas** [comment]
> Google:
> 
>     * `shareable` [276,000,000 hits](https://www.google.com/search?q=shareable)
> 
>     * `sharable` [12,500,000 hits](https://www.google.com/search?q=sharable)
> 
> 
> I really don't know. Perhaps move to _rare_?

I think it's definitely not an error as such, so moving it to _rare_ or deleting it outright sounds good to me. Perhaps there should even be a new dictionary which includes only the "generally preferred" spellings of words?

**Comment by DimitriPapadopoulos** [comment]
I guess the same might be told of other `-able->-eable` fixes.

BTW, there are also incorrect fixes the other way round:
```
resizeable->resizable
```

**Comment by DimitriPapadopoulos** [comment]
Is anyone willing to push a merge request?

**Comment by matkoniecz** [comment]
> Is anyone willing to push a merge request?

I am still waiting for my 2021 merge requests to be processed :)

**Comment by DimitriPapadopoulos** [comment]
@matkoniecz How is this related to this issue?

**Comment by matkoniecz** [comment]
@DimitriPapadopoulos Not strongly related to this specific issue, but is related to request to make a pull request for that issue.

**Comment by DimitriPapadopoulos** [comment]
There is no consensus here, and probably no rules that define how to define and reach consensus. The way out is perhaps to define such rules, not tackle individual cases. Adding comments in unrelated issues will drain time resources that cannot be dedicated to defining such rules.

**Comment by polluks** [comment]
https://books.google.com/ngrams/graph?content=sharable%2Cshareable&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3
