### ISSUE TITLE
Bad correction "dedented" → "indented"

### ISSUE THREAD

**Issue by jwilk** [codespell-project/codespell#2692]
```console
$ echo dedented | codespell -
1: dedented
	dedented ==> indented
```
This is wrong. In Python jargon, "dedent" is the opposite of "indent":
https://en.wiktionary.org/wiki/dedent#Etymology_1
https://docs.python.org/3/library/textwrap.html#textwrap.dedent

**Comment by DimitriPapadopoulos** [comment]
Yes, should probably be moved to _code_, or even removed - what are the odds someone writes `dedent` instead of `indent` unwillingly? Besides, why only `dedent` and not `dedented` or `dedenting`?

Would you like to create a merge request?

**Comment by skangas** [comment]
> Yes, should probably be moved to _code_, or even removed - what are the odds someone writes `dedent` instead of `indent` unwillingly?

Indeed. IMHO, removing it is probably best here.

**Comment by jwilk** [comment]
> Would you like to create a merge request?

Don't count on me, sorry.
