### ISSUE TITLE
Bad correction focussed --> focused, focussing --> focusing

### ISSUE THREAD

**Issue by alexdiem** [codespell-project/codespell#2707]
Focussed for simple past and past participle as well as focussing are correct spellings in British English, see Oxford dictionary: https://www.oxfordlearnersdictionaries.com/definition/english/focus_1?q=focussed

**Comment by DimitriPapadopoulos** [comment]
I can only find `focused` in Oxford Learners' Dictionary, not `focussed`.

**Comment by DimitriPapadopoulos** [comment]
* [Cambridge](https://dictionary.cambridge.org/dictionary/english/focused): both `focused`/`focussed`
* [Collins](https://www.collinsdictionary.com/dictionary/english/focussed): both `focused`/`focussed`
* [Merriam-Webster](https://www.merriam-webster.com/dictionary/focussed): both `focused`/`focussed`
* [Macmillan](https://www.macmillandictionary.com/dictionary/british/focussed): both `focused`/`focussed`

**Comment by alexdiem** [comment]
Maybe you didn't expand on verb forms? 
![image](https://user-images.githubusercontent.com/4499142/212084663-cd91df2f-1caf-4ffb-b23a-90b66fcf02df.png)

**Comment by DimitriPapadopoulos** [comment]
I'm not sure whether I should completely remove the entry or move it to the `en-GB_to_en-US` dictionary.

**Comment by alexdiem** [comment]
I don't know if the spelling is used in American English, but it must be accepted in British English.
