### ISSUE TITLE
convervation -> conservation

### ISSUE THREAD

**Issue by matkoniecz** [codespell-project/codespell#2716]
https://github.com/search?q=Convervation&type=code

**Comment by DimitriPapadopoulos** [comment]
@matkoniecz Do you have past merge requests I could help merging? Is this issue par of such old merge requests?

**Comment by matkoniecz** [comment]
no

**Comment by DimitriPapadopoulos** [comment]
A merge request for this specific case will certainly be merged rapidly.

I recommend you add friends too, if you can find typos in the wild: `convervations`, `convervative`, etc.
