### ISSUE TITLE
"arithmetics" false positive?

### ISSUE THREAD

**Issue by polluks2** [codespell-project/codespell#2717]
"There is decimal arithmetic and binary arithmetic. In fact, there are an infinite number of arithmetic<ins>s</ins> of different bases."
https://en.wiktionary.org/wiki/arithmetics

**Comment by DimitriPapadopoulos** [comment]
This has already been discussed in https://github.com/codespell-project/codespell/pull/1258:
> Similarly if you wrote arithmetics, you probably meant arithmetic, but also you could have itentionally meant arithmetics with an "s"...

Note that this fix is already in the _rare_ dictionary.

**Comment by polluks2** [comment]
I see.

**Comment by DimitriPapadopoulos** [comment]
It's just that we usually base decisions on curated dictionaries such as Oxford, Cambridge, Chambers, Collins, Macmillan, Merriam-Webster, Longman, ...
