### ISSUE TITLE
Question: handling of technical acronyms

### ISSUE THREAD

**Issue by jamesbraza** [codespell-project/codespell#2719]
## Background

Firstly, I love codespell and have managed to get it adopted across the biotech company I work at.  We use lots of chemicals and their abbreviations.  For example, [Acetonitrile](https://en.wikipedia.org/wiki/Acetonitrile) is commonly called "ACN".

One design philosophy of readable code is having one's code mirror the way one speaks.  For example, a chemist might say "flush the chamber with ACN," so a readable code representation might be `instrument.flush_chamber(Fluids.ACN)`.

I have observed codespell tends to flag acronyms like `ACN`.  From https://github.com/codespell-project/codespell/issues/1578#issue-646726101, the current solution is to pass an allow list of lowercase'd acronyms:

```rc
[codespell]
ignore-words-list = acn
```

Currently, I have a steadily growing allow-list of chemical acronyms, which is a perfectly viable solution.

## Question

What is codespell's stance on technical acronyms?  Is there an alternate way of handling a steadily increasing number of technical acronyms (referring to various chemicals)?

Thank you in advance!

**Comment by DimitriPapadopoulos** [comment]
Any misspelled word could ba a valid acronym. I don't really see a solution here, except maintaining your own dictionary of acronyms specific to your domain.

**Comment by jamesbraza** [comment]
Hi @DimitriPapadopoulos thank you for responding!

> Any misspelled word could ba a valid acronym.

Yeah this is a strong point 😆

I know that codespell lowercases everything to avoid the combinatorial explosion of spelling possibilities.  Perhaps there is some way to selectively ignore `CONSTANT_CASE` variable declarations, but I can't think of a good heuristic right now.

Anyways, my question is answered, so I will close this out!  Feel free to re-open if desired.
