### ISSUE TITLE
Checking command line option typos

### ISSUE THREAD

**Issue by szepeviktor** [codespell-project/codespell#2726]
Hello!
I'm a happy user of codespell. Including codespell in CI setups I contribute to open-source projects.

```
#     -m recent --update --seconds 600 --hitcount 6 --name SSHide --rsource \
```
There is a comment in one of my fail2ban config files.
`rsource` is a misspelling included in `data/dictionary.txt`

How can it be found?
changing it to `-- rsource` causes it to be found.

**Comment by szepeviktor** [comment]
* actually `rsource` is a valid iptables option

**Comment by szepeviktor** [comment]
Could the word regex be the cause?
https://github.com/codespell-project/codespell/blob/ea349a2ab846ace712f81b50825942935805d531/codespell_lib/_codespell.py#L31

**Comment by DimitriPapadopoulos** [comment]
We need `-` to catch words such as `auto-detect`.

Perhaps the regex could be modified to not catch leading or trailing dashes. You may define an alternative regex using option `-r`.

**Comment by szepeviktor** [comment]
I think regexp-based operation may ignore some misspellings.
Parsing code may work better https://github.com/crate-ci/typos
