### ISSUE TITLE
False negative: HOSTNAME_CONNNECTION

### ISSUE THREAD

**Issue by jamesbraza** [codespell-project/codespell#2728]
Running `codespell==2.2.2` on this doesn't cause an error:

```python
# NOTE: typo is three N's in connection
HOSTNAME_CONNNECTION = "http://192.168.1.42"
# Same mistake, just lowercase now
hostname_connnection = HOSTNAME_CONNNECTION
```

I think it should?

**Comment by DimitriPapadopoulos** [comment]
Not if the typo is not in the typo dictionary. From [README.rst](https://github.com/codespell-project/codespell/blob/master/README.rst):
> It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf". This also means it shouldn't generate false-positives when you use a niche term it doesn't know about.
