### ISSUE TITLE
Impossible to ignore word "INOUT"

### ISSUE THREAD

**Issue by lovetox** [codespell-project/codespell#2731]
Hi, this should ignore the word, but codespell still shows it as error

`echo "INOUT astroid" | codespell - -L "INOUT,astroid"`

result

```
1: INOUT astroid
	INOUT ==> INPUT, IN OUT
```

this is on git master downloaded today

**Comment by lovetox** [comment]
Surprisingly this works

`echo "INOUT astroid" | codespell - -L "inout,astroid"`

**Comment by DimitriPapadopoulos** [comment]
That's by design. See the README.
