### ISSUE TITLE
Checking only specific file types in specific directories

### ISSUE THREAD

**Issue by cbrnr** [codespell-project/codespell#2772]
I would like to check only specific file types in specific directories, for example just `*.py` and `*.rst` within `src/` and `doc/` (including subdirectories). I assumed that this could be done with

```
codespell src/ doc/ *.py *.rst
```

But this doesn't work, because all kinds of file types are checked (in these directories recursively), and not just *.py and *.rst. Am I misunderstanding something? I think it only works like this (listing individual glob patterns):

```
codespell doc/**/*.rst src/**/*.py
```

**Comment by cbrnr** [comment]
In addition, I would like to use the Codespell GitHub Action as a pre-commit hook, so I was wondering how I can specify to check only specific files and directories. There is a `skip` parameter, but I'd rather specify which files to check instead of which files to skip. Is this possible?

**Comment by DimitriPapadopoulos** [comment]
Why do you think `src/ doc/ *.py *.rst` should work? Below, `[files ...]` is just a list of files or directories:
```sh
$ codespell --help
...
                 [files ...]
$ 
```
In this case, codespell will check all these files or directories:
* `src` (and all its contents)
* `doc` (and all its contents)
* files of the current directory ending with `.py`
* files of the current directory ending with `.rst`

Note that `*.py` will be expanded by the shell if the current directory contains at least one file ending with `*.py`. You should use quotes to avoid expansion by the shell.

**Comment by DimitriPapadopoulos** [comment]
As for you second question, it is not related to [codespell](https://github.com/codespell-project/codespell), but to [actions-codespell](https://github.com/codespell-project/actions-codespell).

See https://github.com/codespell-project/codespell/issues/2758.

**Comment by cbrnr** [comment]
Thanks @DimitriPapadopoulos! For some reason I thought that maybe directories and file patterns would be treated differently, but the second invokation (`codespell doc/**/*.rst src/**/*.py`) works perfectly!
