### ISSUE TITLE
False positive: deque 

### ISSUE THREAD

**Issue by polluks** [codespell-project/codespell#2778]
https://github.com/codespell-project/codespell/blob/e21131469b76f2d290f0134918e28678d2729c5c/codespell_lib/data/dictionary_code.txt#L16
See https://en.wikipedia.org/wiki/Double-ended_queue#Naming_conventions

**Comment by DimitriPapadopoulos** [comment]
This fix is already in `dictionary_code.txt`, not used by default.

**Comment by luzpaz** [comment]
Indeed, because it is a false positive it has been added to the code dictionary.
