### ISSUE TITLE
Please publish GPG keys to verify release tags

### ISSUE THREAD

**Issue by vt-alt** [codespell-project/codespell#2780]
You are GPG-signing your release tags, which is good. But where to get your public key to verify them? Please publish them somewhere, for example on
* https://github.com/larsoner.gpg or https://github.com/codespell-project.gpg or
* on a key server like https://keys.openpgp.org/

Thanks,

**Comment by vt-alt** [comment]
My mistake, release tag is unsigned (because it's not even annotated tag). What is signed is commit under tag `v2.2.4` with `Eric Larson <larson.eric.d@gmail.com>` key.
```
$ git verify-commit v2.2.4
gpg: Signature made Wed 08 Mar 2023 09:58:14 PM MSK
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
```

**Comment by vt-alt** [comment]
Okay, now I realize that this is perhaps just contributor's signature (since this commit is merged) and not of the maintainer of this project. So there is nothing to verify.

In this situation I only could suggest to sign (annotated) release tags in the future then. 
Thanks,

**Comment by DimitriPapadopoulos** [comment]
It is key `4AEE18F83AFDEB23` indeed. The screen capture above states:
> This commit was created on GitHub.com and signed with GitHub’s **verified signature**.
> GPG key ID: 4AEE18F83AFDEB23
> [Learn about vigilant mode](https://docs.github.com/github/authenticating-to-github/displaying-verification-statuses-for-all-of-your-commits).

The public key is published here:
https://github.com/web-flow.gpg

**Comment by vt-alt** [comment]
Ah, I didn't realize that GitHub signs commits with their web-flow signature. Thanks for clarification.

Anyway, signing release tags with **your** signature would be a best practice.

ps. If GitHub signs anybody's commits with their signature, perhaps they can sign any commit on the fork of the repo. This does not look secure at all, unless I miss something.

**Comment by DimitriPapadopoulos** [comment]
Any task done directly on the GitHub web site can only be signed by GitHub, there's no way around that. The alternative would be to perform all tasks remotely, never directly on the web site. But then forget about pull requests and all other bells and whistles that make GitHub so convenient.

If you do not trust GitHub, you may as well leave GitHub – after all! they are admins of their servers!
