### ISSUE TITLE
Allow comments on entries in ignored-words-file 

### ISSUE THREAD

**Issue by pdbj** [codespell-project/codespell#2781]
It would be nice to allow comments on the entries in the `ignore_words_file`:

```
peripherial # from the hash collision table
```

Looks like [this line](https://github.com/codespell-project/codespell/blob/29a4e2af62fb61a3fac163d5b976bd66fe00dc57/codespell_lib/_codespell.py#L624) is the place:

```
for line in f:
    line = line.partition(' #')[0]
    line = line.rstrip()
    ignore_words.add(line)
```

**Comment by DimitriPapadopoulos** [comment]
Duplicate of #2063.
