### ISSUE TITLE
FYI: helper to codespell a project

### ISSUE THREAD

**Issue by yarikoptic** [codespell-project/codespell#2783]
Recently I managed to put myself  to a menial quest to add `codespell` (and now `shellcheck` may be) to some projects I discover or care about.  To facilitate that - prototyped little bash scripts to 
- make a fork on github
- add a remote locally
- create  a branch
- add workflow
- bootstrap config

and later, after fixing things up - send a PR.

Here they are https://github.com/yarikoptic/improveit  happen you would like to make use of smth like that or to generalize into some more generic helper (e.g. `codespell-ci` or alike).

Cheers, feel welcome to close upon reading.

**Comment by kurtmckee** [comment]
@larsoner This issue can be closed.
