### ISSUE TITLE
The new version v2.2.4 generates false positive output

### ISSUE THREAD

**Issue by pirat89** [codespell-project/codespell#2786]
The new codespell version released yesterday started to generate false positives when
* a string is composed dynamically
* when string contains escaped characters , so e.g. following strings are reported as mispelled:

* `"My repositor{suffix} ...".format(suffix=suffix)`
* `'We couldn\'t do ....'`

Additional info:
* https://github.com/oamg/leapp-repository/actions/runs/4383259849/jobs/7673283029
```
Error: ./repos/system_upgrade/common/actors/localreposinhibit/actor.py:60: repositor ==> repository
Error: ./repos/system_upgrade/common/actors/localreposinhibit/actor.py:67: repositor ==> repository
Error: ./repos/system_upgrade/common/actors/checktargetiso/libraries/check_target_iso.py:149: repositor ==> repository
Error: ./repos/system_upgrade/common/actors/selinux/selinuxapplycustom/actor.py:154: couldn ==> could, couldn't
Error: ./repos/system_upgrade/common/actors/selinux/selinuxapplycustom/actor.py:162: couldn ==> could, couldn't
```

**Comment by DimitriPapadopoulos** [comment]
That has always been the case. Are you certain this is a regression?

**Comment by pirat89** [comment]
@DimitriPapadopoulos the mentioned code has been part of the upstream for a longer time and tests (including codespell) have been passing. e.g. like in this one PR https://github.com/oamg/leapp-repository/pull/979 that introduced the chacktargetiso actor. It's visible that it passed originally and now it's failing. Also the previous run in the PR has been ok and it started to faile just today.

It's possible I missed something, but all clues I have seem to be suggesting it's regression.

**Comment by DimitriPapadopoulos** [comment]
OK, let me see:
```
$ cat > foo.bar.txt
My repositor{suffix}
We couldn\'t do
$ 
```
With codespell 2.2.2:
```
$ codespell foo.bar.txt
$ 
```
With codespell 2.2.3:
```
$ codespell foo.bar.txt
foo.bar.txt:1: repositor ==> repository
foo.bar.txt:2: couldn ==> could, couldn't
$ 
```

It's just that `repositor` and `couldn` have been added to the dictionary of typos.

**Comment by DimitriPapadopoulos** [comment]
This does raise the question of dictionary updates, especially in CI actions.

**Comment by pirat89** [comment]
@DimitriPapadopoulos thanks for the info. Make sense. So I will add it to the ignorelist in our projects.

**Comment by bdice** [comment]
Even without escape characters, it seems like `couldn't` gets replaced with `couldn't't` in several of my projects, because of the rule `couldn->couldn't` in https://github.com/codespell-project/codespell/pull/2660. This feels like an unwanted dictionary behavior. Is there a way to conditionally handle this, like `couldn ->couldn't ` with a space or some other character following? I would be happier with this rule if it ignored the case where `couldn` was followed by an apostrophe.
