### ISSUE TITLE
Incorrect spelling suggestion for the Angolan currency Kwanza

### ISSUE THREAD

**Issue by cclauss** [codespell-project/codespell#2794]
https://en.wikipedia.org/wiki/Angolan_kwanza
https://en.wikipedia.org/wiki/Kwanza,_Kenya
https://en.wikipedia.org/wiki/Kwanzaa

The newest release of codespell requests this change:
* web_programming/currency_converter.py:26: Kwanza ==> Kwanzaa

Clearly, both are valid spellings for different things.
* https://en.wikipedia.org/wiki/Kwanza_(disambiguation)

**Comment by DimitriPapadopoulos** [comment]
Yes, makes sense. Do not hesitate to suggest a merge request to fix that.
