### ISSUE TITLE
`--skip` Doesn't Ignore Folders Appended With `/`

### ISSUE THREAD

**Issue by Casey-Kiewit** [codespell-project/codespell#2799]
The following doesn't ignore a folder called `example`:

```shell
codespell --skip="example/" .
```

Would appreciate the thoughts of the core developers on this project on whether this is truly unintended behavior or not, but this is somewhat unexpected coming from most other command-line tools I've used. I'm happy to try to address this if this is indeed unintended behavior.

**Comment by DimitriPapadopoulos** [comment]
Yes, that's part of the issues described in #2047, which I had attempted to fix in #2058. Unfortunately, all my changes had been lost while addressing endless requests to rework tests to add new edge cases. I need to restart working on that PR.
