### ISSUE TITLE
allow code-annotations for locally flagging false positives

### ISSUE THREAD

**Issue by umlaeute** [codespell-project/codespell#2828]
it would be great if we could add annotations into the code in order to prevent the detection of false-positives.

sometimes you just do not have any choice of wording, but still do not want to add a global ignore for a given word.

something like this:

```C
struct v4l2_streamparm param.
// codespell-ignore parm
param.parm.capture.timeperframe.numerator = 1;
```

suggested keywords (just ideas; alternatively map the cmdline args, or whatever; though I quite like the possibility to *end* additional ignore-rules)
- `codespell-ignore` start ignoring the given words within the current file
- `codespell-unignore` start ignoring the given words within the current file (falling back to the original state, as defined via the cmdline)
- `codespell-ignoreonce` only ignore the next occurence of the word

this would also help to run `codespell` without any arguments

**Comment by umlaeute** [comment]
ouch, thanks for spotting this.
i *did* search the issue tracker first, but unfortunately used the wrong search terms.

**Comment by DimitriPapadopoulos** [comment]
@umlaeute You're welcome. Thank you for helping out.
