### ISSUE TITLE
Add regex option to run in codespell yml

### ISSUE THREAD

**Issue by jackiekazil** [codespell-project/codespell#2851]
We ran into the same issue with the jupyter notebooks that other folks have (Re: #2138) 
There were four of us at Pycon us 2023 troubling shooting this -- there are a lot of rapid PRs and then reverts around this -- the trail can be found here: 

https://github.com/projectmesa/mesa/issues/1661 

tldr; You can run a regex on the command line, but the same regex does not work in the codespell.yml and if it does it is not documented, so we didn't know which variable to use... we guessed. 

[This is the regex](https://github.com/projectmesa/mesa/pull/1668/files#diff-ce84a1b2c9eb4ab3ea22f610cad7111cb9a2f66365c3b24679901376a2a73ab2R19 ) that worked on the commandline to basically ignore images & pngs that were in the jupyter notebook

`ignore_regex: ^\s*"image\/png":\s.*`

And here is [an example of the jupyter notebook output that is causing false errors](https://github.com/projectmesa/mesa/pull/1668/files#file-docs-tutorials-intro_tutorial-ipynb-L877 ). 

Hot take: I don't know that codespell needs to figure out how to solve for jupyter notebooks - that seems like a secondary library that should exist like codespell-notebooks (or something else), but I think the regex that works on the commandline should work in the .yml file. 

We got it to work by just [ignoring jupyter notebooks in our docs folder](https://github.com/projectmesa/mesa/pull/1670/files#diff-ce84a1b2c9eb4ab3ea22f610cad7111cb9a2f66365c3b24679901376a2a73ab2R18): 
`skip: .*bootstrap.*,*.js,.*bootstrap-theme.css.map,./docs/*.ipynb`

Let me know if you have any questions. I hope links I provided makes this and easier fix to navigate.

**Comment by DimitriPapadopoulos** [comment]
Oh, I get it. THis is about the [actions-codespell](https://github.com/codespell-project/actions-codespell) Git Hub Action.

You might want to have a look at issues such as https://github.com/codespell-project/actions-codespell/issues/42, and i needed, open a new issue here:
https://github.com/codespell-project/actions-codespell/issues

**Comment by jackiekazil** [comment]
Thank you. That covers it. I am going to close this issue.
