### ISSUE TITLE
Add gauranttee->guarantee

### ISSUE THREAD

**Issue by janosh** [codespell-project/codespell#2857]

**Comment by luzpaz** [comment]
Make a PR?

**Comment by janosh** [comment]
I'll accumulate some words and then make a batched PR. So much overhead to do a PR for every single correction.

**Comment by luzpaz** [comment]
Don't forget to add `Closes #2857` when you make the PR to autoclose this ticket. TIA

**Comment by janosh** [comment]
traned -> trained

**Comment by DimitriPapadopoulos** [comment]
And friends:
```
gaurantteed->guaranteed
gauranttees->guarantees
traning -> training
```

**Comment by janosh** [comment]
equillibriation -> equilibriation

**Comment by janosh** [comment]
dictionarty -> dictionary

**Comment by janosh** [comment]
erturn >return

**Comment by janosh** [comment]
permuataions->permutations

**Comment by janosh** [comment]
molelcule->molecule

**Comment by janosh** [comment]
Compatiblity -> Compatibility
