### ISSUE TITLE
A list of new mispellings

### ISSUE THREAD

**Issue by Jeremiah-England** [codespell-project/codespell#2868]
A coworker was taking over some of my old code and found a lot of misspellings in it... I'm looking into tools to help fix my issue (lol). I found that `codespell` catches a lot of them! However, there were a few that it missed.

```
acculumating -> accumulating
anualized -> annualized
assset -> asset
avialible -> available
baises -> biases
cliped -> clipped
curature -> curvature
depdencencies -> dependencies
eveything -> everything
formuala -> formula
multpile -> multiple
pararm -> param
poin -> point
segmnet -> segment
termonology -> terminology
tolearnce -> tolerance
traids -> triads
tupes -> tuples
```

I'm not sure that all of these are good candidates, but probably some of them are! I thought I would just paste them all here to see if you think any of them are worth adding.

**Comment by DimitriPapadopoulos** [comment]
Sure, can you prepare a pull request? I recommend adding plural/singular forms and all verbal forms where appropriate.

**Comment by Jeremiah-England** [comment]
Yes, I'll put making a PR my todo list. I will most likely get to it next weekend but possibly before.

Thanks!

**Comment by DimitriPapadopoulos** [comment]
@Jeremiah-England As long as you have time, please feel free to make a pull request.
