### ISSUE TITLE
`.ser` extension: typo?

### ISSUE THREAD

**Issue by jamesbraza** [codespell-project/codespell#2888]
Currently, `codespell==v2.2.5` is flagging `ser` as a typo of `set`.

`.ser` is an extension for serialized files.

Should this be removed from the dictionary?

**Comment by DimitriPapadopoulos** [comment]
I don't think it should be removed from the dictionary. The typo appears to be occurring often. The file extension is less common and in that case `ser` can be added to the skip list.

**Comment by peternewman** [comment]
We could move it to the code dictionary though...

**Comment by jamesbraza** [comment]
Up to you all! I can make a PR to add to code dictionary, otherwise feel free to close this out

**Comment by DimitriPapadopoulos** [comment]
I didn't know about `.ser`, it seems some programmers serialize Java objects to files with that extension, without that extension being a standard. I would rather keep the dictionaries as they are.
