### ISSUE TITLE
Undocumented Dev Dependencies

### ISSUE THREAD

**Issue by Casey-Kiewit** [codespell-project/codespell#2896]
While working on https://github.com/codespell-project/codespell/issues/2877, I noticed that a few additional dependencies aren't currently documented or listed as dev dependencies. These also seem to be fine to install without Aspell, resulting the the checks being skipped as normal.

The additional dependencies required if Aspell is installed for additional testing:
- aspell-python-py3
- twine

**Comment by Casey-Kiewit** [comment]
@DimitriPapadopoulos @larsoner Are you two opposed to me adding both these as dev dependencies or are there some ramifications to this I'm not aware of? Alternatively, I could add documentation for this in the README.

**Comment by peternewman** [comment]
I don't know about twine, but the main aim with not including aspell was to stop every individual having to pull it in when they just want to add a dictionary entry, given the majority won't be in there anyway. aspell is really just a further safety net that we haven't accidentally added some obscure word as a typo.

**Comment by DimitriPapadopoulos** [comment]
@Casey-Kiewit Indeed `twine` should have been added to the dev dependencies in #2626. A merge request to add it would be great.

**Comment by larsoner** [comment]
Agreed
