### ISSUE TITLE
Aspell Tests Failing On Debian 12

### ISSUE THREAD

**Issue by korverdev** [codespell-project/codespell#2897]
The error I'm running into on Debian 12:
```shell
______________ test_dictionary_formatting[/workspaces/codespell/codespell_lib/tests/../data/dictionary.txt-in_aspell0-in_dictionary0] ______________
codespell_lib/tests/test_dictionary.py:70: in test_dictionary_formatting
    raise AssertionError("\n" + "\n".join(errors))
E   AssertionError: 
E   error 'dateset' should not be in aspell dictionaries (en, en_GB, en_US, en_CA, en_AU) for dictionary /workspaces/codespell/codespell_lib/tests/../data/dictionary.txt
------------------------------------------- generated xml file: /workspaces/codespell/junit-results.xml --------------------------------------------
========================================================== 1 failed, 44 passed in 13.90s ===========================================================
```
On Debian 11, all tests pass.

I suspect this is caused by an update to the `aspell` package from `0.60.8-3` -> `0.60.8-4+b1`.

**Comment by DimitriPapadopoulos** [comment]
It looks like dateset has been added to recent aspell dictionaries. Yet it's not a word, as far as I know. Some hits which I believe are not common enough to consider it not a common typo:
* [DateSet](https://www.dateset.io/)
* .NET [DatePickerDialog.DateSet Event](https://learn.microsoft.com/en-us/dotnet/api/android.app.datepickerdialog.dateset)

By the way, I wonder whether we should change `dateset->dataset` into `dateset->dataset, date set,`.

**Comment by DimitriPapadopoulos** [comment]
The obvious fix would be to move `dateset` to _rare_.
