### ISSUE TITLE
`process's` or `process'`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#2928]
https://github.com/codespell-project/codespell/blob/94dfe1859e15d43d248118811dc5589b55a4a71b/codespell_lib/data/dictionary_code.txt#L53

Later versions of the [U.S. Government Publishing Office Style Manual](https://www.govinfo.gov/collection/gpo-style-manual) suggest the _s_ is dropped.

[2008](https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2008/)
> #### Apostrophes and possessives
>  **8.3.** The possessive case of a singular or plural noun not ending in _s_ is formed by adding an apostrophe and _s_. The possessive case of a singular or plural noun ending in _s_ or with an _s_ sound is formed by adding an apostrophe only.
> [...]
> boss’, bosses’
> [...]

[2000](https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2000/)
> #### Apostrophes and possessives
> **8.3.** All singular nouns form their possessive case by the addition of an apostrophe and an _s_. Plural nouns ending in _s_ form their plurals by adding only an apostrophe.
> [...]
> boss’s, bosses’
> [...]

Perhaps it's time we drop such fixes, especially those that are wrong any way (`files'->file's` could be plural):
```
$ grep -R "s'->" codespell_lib/data/
codespell_lib/data/dictionary.txt:aircrafts'->aircraft's
codespell_lib/data/dictionary.txt:gaus'->Gauss'
codespell_lib/data/dictionary.txt:guas'->Gauss'
codespell_lib/data/dictionary.txt:guass'->Gauss'
codespell_lib/data/dictionary.txt:packges'->packages'
codespell_lib/data/dictionary.txt:thats'->that's
codespell_lib/data/dictionary_code.txt:files'->file's
codespell_lib/data/dictionary_code.txt:process'->process's
codespell_lib/data/dictionary_code.txt:subprocess'->subprocess's
```

**Comment by isaak654** [comment]
I agree, plus this correction produces unnecessary warnings:
`SBIEMSG.js:13: process' ==> process's`
Line 13 of SBIEMSG.js:
`{ id: 'process', name: tr('Name affected process'), type: 'edit', hint: 'Program.exe when applicable' },`

By the way, how should I exclude this detection? Do I need to insert `--ignore-words-list="process'"` ?
