### ISSUE TITLE
Keep the tab open

### ISSUE THREAD

**Issue by janosh** [codespell-project/codespell#2938]
New growing collection similar to https://github.com/codespell-project/codespell/issues/2857.

To start off:
- polymoprh->polymorph
- encouraed->encouraged
- explanantion->explanation
- verbossity->verbosity
- Agrs->Args
- efficience->efficiency
- frational->fractional

**Comment by kurtmckee** [comment]
[vor->for](https://github.com/jazzband/pip-tools/blob/31ea3fb8eb65ec2c2fdcfd6fa281f54d480225b8/README.md?plain=1#L303)

**Comment by kurtmckee** [comment]
I think I may have misunderstood; I thought this was collecting suggestions. :sweat:

I'll submit a PR later to suggest this addition. :+1:

**Comment by janosh** [comment]
- oriended->oriented

**Comment by janosh** [comment]
- capcity->capacity
- graviometric->gravimetric

**Comment by janosh** [comment]
matricies->matrices

**Comment by janosh** [comment]
latice->lattice

**Comment by janosh** [comment]
orthorombic->orthorhombic

**Comment by kurtmckee** [comment]
This issue is closed. I recommend opening a new issue that'll be visible to others.

**Comment by janosh** [comment]
This issue is just for note-taking so I can add stuff in batches later. No need for others to see.

**Comment by janosh** [comment]
This issue is just for note-taking so I can add stuff in batches later. No need for others to see.

**Comment by kurtmckee** [comment]
Ah, got it. I was subscribed due to previous participation, but it's easy to unsubscribe! :grinning: :+1:

**Comment by janosh** [comment]
genenerated->generated
