### ISSUE TITLE
Update pre-commit hooks

### ISSUE THREAD

**Issue by korverdev** [codespell-project/codespell#2958]
I can handle this one when I get some time, but wanted to create an issue to keep track of this. It looks like the following are due for an update:
- [ ] yamllint
- [ ] ruff - Pending https://github.com/codespell-project/codespell/issues/2960.
- [ ] autoflake
- [ ] codespell
- [ ] validate-pyproject
- [ ] mypy

**Comment by DimitriPapadopoulos** [comment]
See #2967.
