### ISSUE TITLE
Ruff checks failing on `master`

### ISSUE THREAD

**Issue by korverdev** [codespell-project/codespell#2960]
It appears something's changed with the latest version of ruff, [causing the server-side checks to fail with the following output](https://github.com/codespell-project/codespell/actions/runs/5639052570/job/15273804468):
```
codespell_lib/_codespell.py:1003:5: PLR0912 Too many branches (49 > 48)
```

I was able to recreate this locally. `v0.0.254` of the Pre-Commit hook passes all checks, but the latest version, `v0.0.280`, raises the same error.

**Comment by korverdev** [comment]
Opened a separate issue to discuss a potential long-term solution for this and similar issues:
https://github.com/codespell-project/codespell/issues/2961

**Comment by DimitriPapadopoulos** [comment]
Indeed ruff is still evolving rapidly resulting in new CI alerts without actual changes in our codebase. You just need to change:
```
max-branches = 48
```
to:
```
max-branches = 49
```

Or, alternatively, you can reorganise the code to remove branches, although I don't see anything wrong with multiple similar branches when parsing command line options.
