### ISSUE TITLE
Consider using Pre-Commit for CI checks

### ISSUE THREAD

**Issue by korverdev** [codespell-project/codespell#2961]
Currently, for local checks, this project uses Pre-Commit with pinned versions of particular libraries. Most of the important checks are also confirmed server-side by GitHub actions. Breakage from a version update reported in https://github.com/codespell-project/codespell/issues/2960 goes over one of the core problems with this approach. Additionally, some Pre-Commit checks, albeit minor ones, aren't being confirmed server-side.

I'd like to drop the existing CI checks for individual quality checks in favor of running them all through Pre-Commit in a single action. This will allow for managing these versions through Pre-Commit in all cases. If this is a change this project is interested in making this change, I'd be happy to put together a PR for this.

**Comment by DimitriPapadopoulos** [comment]
See https://github.com/codespell-project/codespell/pull/2967#issuecomment-1649827285.
