### ISSUE TITLE
ruff is causing PR checks to fail

### ISSUE THREAD

**Issue by int-y1** [codespell-project/codespell#3014]
PR checks are failing on "Run make check" due to this error:

```
ruff .
Error: codespell_lib/_codespell.py:194:17: PLE1300 Unsupported format character '}'
make: *** [Makefile:42: ruff] Error 1
Error: Process completed with exit code 2.
```

Recently, the ruff version increased from `ruff-0.0.282` to `ruff-0.0.283`. Either fix the Python code, or downgrade ruff.

**Comment by DimitriPapadopoulos** [comment]
The relevant line is:
https://github.com/codespell-project/codespell/blob/c5febe68414ac95f54fc9a8df1d9cc51fca8de65/codespell_lib/_codespell.py#L194

The above Python code seems legal to me. From [Format String Syntax](https://docs.python.org/3/library/string.html#format-string-syntax):
> A _format_spec_ field can also include nested replacement fields within it. These nested replacement fields may contain a field name, conversion flag and format specification, but deeper nesting is not allowed.

@int-y1 Do you have reasons to believe the Python code needs to be fixed? If that were the case, I would rather fix the Python code.
