### ISSUE TITLE
Feature: CI test for missing commas in dictionary.txt

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#303]
In #302 I mention a regex that tests `dictionary.txt` for missing commas in multi-answer typos. I suggest we have a CI test that executes ` ^(?=\w+->(?!\w+$)(?:\w+, )*\w+(?!,)$).+` to test for missing commas and reports it clearly. 
```
amin->main, disabled because of var names
clas->class, disabled because of name clash in c++
cmo->com, disabled due to lots of false positives
gonna->going to, disabled because one might want to allow informal spelling
pass-thru->pass-through, pass through, passthrough
pass-trough->pass-through, pass through, passthrough
```

The above regex is intelligent enough to distinguish the above examples not as false positives:
https://regex101.com/r/Mz4piI/1

**Comment by flopp** [comment]
#701 checks for all kinds of comma errors, including missing commas.
