### ISSUE TITLE
corrections in an other language than English

### ISSUE THREAD

**Issue by pinsardfr** [codespell-project/codespell#3037]
As a part of my projects are used in France,  we used French words in our comments.
I do not understand why words like projects, environnement, espace, exemple (French words) are detected as typo.

 ```bash
echo "projets" | codespell -
1: projets
        projets ==> projects
```

In the same time, real French typos are not detected 
```bash
echo "pojets" | codespell -
```

In this case it would be nice to have 
```bash
echo "pojets" | codespell -
1: pojets
        pojets ==> projects
```

Could you help me to setup codespell options to avoid French false positive typos and detect real ones ?

**Comment by DimitriPapadopoulos** [comment]
Codespell provides dictionaries of English typos only:
https://github.com/codespell-project/codespell/tree/master/codespell_lib/data/

You would have to create your own dictionaries of typos:
* a dictionary with common French typos only,
* in a mixed-language environment, the English codespell dictionaries, with all French words removed.

I suspect codespell does not really fit your use case.

**Comment by peternewman** [comment]
> Codespell provides dictionaries of English typos only: https://github.com/codespell-project/codespell/tree/master/codespell_lib/data/
> 
> You would have to create your own dictionaries of typos:
> * in a mixed-language environment, the English codespell dictionaries, with all French words removed.

We could split those out without too much trouble (but a chunk of work or automation) by moving every typo that was in the aspell-fr one to another dictionary. Which might also help our dictionary size issues...

Although I guess its a rather niche feature unless someone is planning to manage a French dictionary...
 
> I suspect codespell does not really fit your use case.

I'd have thought it would work okay if someone created a French dictionary.

**Comment by DimitriPapadopoulos** [comment]
Can we split the English dictionaries just for French? Ideally we should take into account "all" languages. On the other hand many English words derive but differ from French, which is a large source of English typos and errors for French speakers.

In any case, there's no way to "set up codespell" in the short term, apart from creating French dictionaries of typos.
