### ISSUE TITLE
Use SCOWL's `varcon.txt` for en_GB → en_US conversion

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [codespell-project/codespell#3061]
Either use [`varcon/varcon.txt`](https://github.com/en-wl/wordlist/blob/master/varcon/varcon.txt) directly, or use it to generate the current [`codespell_lib/data/dictionary_en-GB_to_en-US.txt`](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_en-GB_to_en-US.txt).

**Comment by vikivivi** [comment]
Also see https://github.com/codespell-project/codespell/issues/1917
