### ISSUE TITLE
labourer => laborer?

### ISSUE THREAD

**Issue by SimonVerhoeven** [codespell-project/codespell#3127]
Currently, https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_en-GB_to_en-US.txt contains:

```
labour->labor
laboured->labored
labours->labors
```

Wouldn't ideally labourer -> laborer and labourers -> laborer also be in there?

I'm happy to add them if you agree.

**Comment by DimitriPapadopoulos** [comment]
Also `labouring` to have all verbal forms.
