### ISSUE TITLE
h

### ISSUE THREAD

**Issue by MadMax1311** [codespell-project/codespell#3151]

**Comment by DimitriPapadopoulos** [comment]
@MadMax1311 Once, error is human. Twice, slow-witted? Thrice, you're definitely a moron.

**Comment by peternewman** [comment]
@DimitriPapadopoulos did you mean the hacktoberfest label, not spam/invalid:
https://hacktoberfest.com/participation/#maintainers

See also the similar bit in the FAQ:
https://hacktoberfest.com/participation/#faq

**Comment by DimitriPapadopoulos** [comment]
We do not have a "spam" label. Hacktoberfest is behind these spammy pull requests and issues. For its 10th anniversary, Hacktoberfest has clearly become fashionable among wannabee developers who like to display them in their accounts. I feel Hacktoberfest has become a nuisance more than an opportunity.

I am happy to change the label to "spam" once it is available.

**Comment by DimitriPapadopoulos** [comment]
Actually I have been able to crate a "spam" label. It might indeed help report identify clueless spammers like this one, and prevent them from getting badges to display in their accounts.

**Comment by peternewman** [comment]
> Actually I have been able to crate a "spam" label. It might indeed help report identify clueless spammers like this one, and prevent them from getting badges to display in their accounts.

Yeah sorry I wasn't very clear about the fact you'd be able to create a label. I've restyled it to make it a bit more generic/futureproof.

I guess given we've been featured in that other video, then changes might be futile, but we could always drop out and just explicitly assign `hacktoberfest-accepted` if we got any particularly worthy contributions...

**Comment by MadMax1311** [comment]
please remove spam label

**Comment by luzpaz** [comment]
reporting @MadMax1311 to github
