### ISSUE TITLE
C++ `std::stoll` reported as spell error

### ISSUE THREAD

**Issue by david-alvarez-rosa** [codespell-project/codespell#3153]
I'm trying to run `codespell` in a C++ project, and I'm getting `std::stoll` ([ref.]) reported as spelling error.

```text
stoll ==> still
```

[ref.]: https://en.cppreference.com/w/cpp/string/basic_string/stol

**Comment by david-alvarez-rosa** [comment]
I'm using the following .codespellrc` file

```text
[codespell]
builtin = clear,rare,en-GB_to_en-US,names,informal,code
check-filenames =
check-hidden =
skip = */.git,*/build,*/prefix
quiet-level = 2
```

that I've copy / past from a best practices repo https://github.com/friendlyanon/cmake-init-shared-static/blob/master/.codespellrc

**Comment by DimitriPapadopoulos** [comment]
Add this to `.codespellrc`:
```ini
ignore-words-list = stoll
```

**Comment by david-alvarez-rosa** [comment]
Thank you Dimitri!

Also, after changing my config file to

```
[codespell]
skip = */.git,*/build
```

it's working fine.

**Comment by DimitriPapadopoulos** [comment]
I guess we could move `stoll` to the _code_ dictionary. It's difficult to strike the right balance.
