### ISSUE TITLE
"lowercased" false positive

### ISSUE THREAD

**Issue by polluks** [codespell-project/codespell#3181]
lowercase
    [verb](https://www.merriam-webster.com/dictionary/verb)
    lowercased; lowercasing

[transitive verb](https://www.merriam-webster.com/dictionary/transitive)
: to print or set in lowercase letters

https://www.merriam-webster.com/dictionary/lowercase

**Comment by DimitriPapadopoulos** [comment]
It's also in [OED](https://www.oed.com/search/dictionary/?q=lowercased), but is missing from [SCOWL (And Friends)](http://app.aspell.net/lookup?dict=en_GB-large;words=lowercased). Perhaps it should be in the _rare_ dictionary.

@polluks But wait, I cannot find `lowercased` in any our dictionaries of typos. It looks like it was removed back in 2019 (#837).
