### ISSUE TITLE
Name Manuel is falsely reported

### ISSUE THREAD

**Issue by georgkrause** [codespell-project/codespell#3202]
Since the latest version codespell tries falsely reports our Developer Manuel to be written wrong and tries to correct this to `manual`.

I am not sure if a common name should be included in the data as a wrong spelling.

**Comment by DimitriPapadopoulos** [comment]
Yes, I've seen that myself today in [pandas](https://github.com/pandas-dev/pandas).

What can I say? Lots of typos might be actual names of places or people in different cultures. See for example #2812. It's a thin line between having no false positives but but lots of false negatives, and having fewer false negatives at the expense of more false positives. I would even acknowledge a cultural bias: proper nouns outside the traditional English-speaking cultural sphere may be at a disadvantage. I don't have an easy solution to suggest. In this specific case, perhaps we could move `manuel` to the _rare_ dictionary, but then the name Manuel is not rare. I've seen collisions between a typo and a name in many large projects, they are usually handled by adding the specific typo to the list of words to ignore.

**Comment by peternewman** [comment]
We've a dictionary for that already, the names one, we just need to move it to there:
https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary_names.txt

**Comment by DimitriPapadopoulos** [comment]
I hadn't noticed this small dictionary, thank you for poiting us to it.

@georgkrause A PR moving `manuel` to the _names_ dictionary would be most welcome.

**Comment by hugovk** [comment]
Please see PR #3204.
