### ISSUE TITLE
"crossreference", a rare candidate?

### ISSUE THREAD

**Issue by polluks** [codespell-project/codespell#3203]
https://en.wiktionary.org/wiki/crossreference
https://books.google.com/ngrams/graph?content=crossreference%2Ccross-reference&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3

**Comment by DimitriPapadopoulos** [comment]
Yes, looks like a rare candidate, as I can find it in [OED](https://www.oed.com/search/dictionary/?q=crossreference).

**Comment by polluks** [comment]
As you like it...
