### ISSUE TITLE
.codespellrc file doesn't work

### ISSUE THREAD

**Issue by jcubic** [codespell-project/codespell#3216]
I just added a config file from the command that I used to ignore node_modules (that should be ignored by default even if it's a Python tool).

<details>
<summary>Unreadable video</summary>

![Peek 2023-11-14 18-46](https://github.com/codespell-project/codespell/assets/280241/6df4042f-09ac-4c00-b7cb-d5d7001a12bd)
</details>

**Comment by DimitriPapadopoulos** [comment]
How doesn't it work?

**Comment by jcubic** [comment]
It process node_module directory that is in skip:

this is part of the log:
```
/node_modules/@puppeteer/browsers/lib/cjs/fileUtil.js.map:1: AAdD ==> add
./node_modules/@puppeteer/browsers/lib/cjs/fetch.js.map:1: EACf ==> each
./node_modules/@puppeteer/browsers/lib/cjs/fetch.js.map:1: EACf ==> each
./node_modules/@puppeteer/browsers/lib/cjs/launcher.js.map:1: EACf ==> each
./node_modules/@puppeteer/browsers/lib/cjs/launcher.js.map:1: EACf ==> each
./node_modules/@puppeteer/browsers/lib/cjs/launcher.js.map:1: EACf ==> each
./node_modules/@puppeteer/browsers/lib/cjs/launcher.js.map:1: CACH ==> CATCH, CACHE
./node_modules/@puppeteer/browsers/lib/cjs/launcher.js.map:1: CACL ==> CALC
./node_modules/@puppeteer/browsers/lib/cjs/launcher.js.map:1: CACL ==> CALC
./node_modules/@puppeteer/browsers/lib/cjs/CLI.js.map:1: CACL ==> CALC
./node_modules/@puppeteer/browsers/lib/cjs/CLI.js.map:1: DAA ==> DATA
```

This also doesn't work: `codespell --config .codespellrc` it process node_modules.

**Comment by DimitriPapadopoulos** [comment]
This works for me:
```ini
[codespell]
skip = ./node_modules*,./assets/*,./dist/*,./package-lock.json,./lib/srfi/*
```

**Comment by DimitriPapadopoulos** [comment]
```
$ cat .codespellrc 
[codespell]
skip = ./node_modules*,./assets/*,./dist/*,./package-lock.json,./lib/srfi/*
$ 
$ cat node_modules/fileUtil.js.map 
AAdD
$ 
$ codespell
$ 
$ rm .codespellrc 
$ 
$ codespell 
./node_modules/fileUtil.js.map:1: AAdD ==> add
$ 
```

**Comment by jcubic** [comment]
It doesn't work on my Fedora. Do you have codespell installed from pip, or do you execute it from source?

**Comment by DimitriPapadopoulos** [comment]
Have you seen the difference between our `.codspellrc` files? My post was unclear, I actually changed the `.codespellrc` file.

**Comment by jcubic** [comment]
Yes I've seen the quotes

**Comment by jcubic** [comment]
ok, I've found the error I had missing comma, I've deleted assets directory in same time. A silly mistake. Sorry for the trouble. The tools is great, thanks for creating it.
