### ISSUE TITLE
"--interactive" useless without "-w"

### ISSUE THREAD

**Issue by buhtz** [codespell-project/codespell#3220]
I tried `codespell -i 3` to check errors and select modifications offered by codespell.
But the files are not modified even if I have chosen `Y`.

It only works when I add `-w`.

From a users perspective I would expect that `-i` implicates `-w`.

**Comment by MercuryDemo** [comment]
hi, can i work on this issue？I'm looking for my first issue on github.

**Comment by buhtz** [comment]
Damn. Run again into this bug and wasted half hour of my lifetime.

Suggestion: If you disagree that "-i" should implicate "-w" then minimally there should be warning when using "-i" without "-w".

**Comment by DimitriPapadopoulos** [comment]
I'd be happy to merge #3220 once the issues have been fixed.

**Comment by DimitriPapadopoulos** [comment]
Closed by #3340.
