### ISSUE TITLE
Feature request: support for lapce editor

### ISSUE THREAD

**Issue by zero-pytagoras** [codespell-project/codespell#3223]
Hi,
there is new editor on the horizon, that is getting a momentum called [lapce](https://lapce.dev)
will be possible to port codespell to it ?

**Comment by DimitriPapadopoulos** [comment]
Lots of things are possible with adequate effort. Note that codespell currently checks files, not a buffer in memory.

**Comment by DimitriPapadopoulos** [comment]
You could try to adapt this function to operate both on a file and a buffer in memory, not only a file:
https://github.com/codespell-project/codespell/blob/085a69752a64fc24f155a69881cd28ecaa9bda96/codespell_lib/_codespell.py#L820

**Comment by DimitriPapadopoulos** [comment]
Perhaps [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (LSP) is of interest.
