### ISSUE TITLE
pyproject.toml: : How to set private dictionary and standard dictionnary at the same time?

### ISSUE THREAD

**Issue by mdeweerd** [codespell-project/codespell#3285]
`pyproject.toml` is at least tricky to setup the equivalent of the following CLI call:

```shell
codespell --dictionary - --dictionary path/to/localdict .
```

I tried the equivalents of the following (and other combinations):
```ini
[tool.codespell]
dictionary  = "-"
dictionary = "dev/tools/codespell/codespell-dict.txt"
```

```ini
[tool.codespell]
D = "-"
dictionary = "dev/tools/codespell/codespell-dict.txt"
```

I did not find documentation on how to specify this in `pyproject.toml`.

Maybe there is another way to achieve this?

**Comment by mdeweerd** [comment]
It could have a common solution but it's for .codespellrc.

I had also tried:
```yaml
[tool.codespell]
dictionary = "-,dev/tools/codespell/codespell-dict.txt"
```
but then I get
```
codespell: error: argument -D/--dictionary: expected one argument
```

I have version 2.2.6 and tomli installed.

**Comment by DimitriPapadopoulos** [comment]
It's the same issue. Let's continue in https://github.com/codespell-project/codespell/issues/2727.
