### ISSUE TITLE
Force case of words ? Example: wednesday->Wednesday

### ISSUE THREAD

**Issue by mdeweerd** [codespell-project/codespell#3288]
I tried to force the case of a word in a project and then checked the standard directory for examples.

I find that there are corrections to Wednesday with an initial capital, but none to correct the uncapitalized word to the same with a capital letter.
So I conclude that I can not create a custom rule like that either.

I checked the issues, I could not find another (including closed) discussion about this.

Is there a proper method to add a rule similar to wednesday->Wednesday ?

**Comment by DimitriPapadopoulos** [comment]
codespell does not fix capitalisation. Fixes use the same capitalisation as the typos:
```
wedensday ==> wednesday
Wedensday ==> Wednesday
```

**Comment by mdeweerd** [comment]
Ok, thank you for the feedbak.
