### ISSUE TITLE
Question: how can I create a space seperated word in a dictionary?

### ISSUE THREAD

**Issue by commodis** [codespell-project/codespell#3342]
```sh
cat dictionary.txt
"mime type"->mediatype
mime type->mediatype

cat example.txt
In this line the mime type should be called media type.

codspell --dictionary dictionary.txt
```

does not match against a file containing `mime type`. 

Is this currently possible? Looking at https://github.com/codespell-project/codespell/issues/3305#issuecomment-1908891783 it seems not possible because it parses by words and thus only the words `mime` and `type` are identified and the context is lost?

**Comment by DimitriPapadopoulos** [comment]
Indeed, _codespell_ currently operates on single words. Operating on N-grams would be a nice improvement, but that would be a major change.
