### ISSUE TITLE
remove `crate -> create`

### ISSUE THREAD

**Issue by janosh** [codespell-project/codespell#3355]
"crate" is a common word in programming (think [rust crates](https://crates.io/)) and should not be in the default set of corrections

**Comment by DimitriPapadopoulos** [comment]
It's already in the _rare_ dictionary, see #2281. Its place is between the _code_ and _rare_ dictionaries, there's no easy solution as far as I can see.

**Comment by janosh** [comment]
not sure i would put it in `code` as that's where this correction is most likely to be unwanted. since it shouldn't be in the default set imo, maybe just remove it altogether?

**Comment by DimitriPapadopoulos** [comment]
That's precisely why it **should** be in `code`.
