### ISSUE TITLE
Redundant sort test

### ISSUE THREAD

**Issue by korverdev** [codespell-project/codespell#3359]
I wanted to create an issue to discuss with the maintainers of this repo before I went ahead and deleted a test, but it appears this project is using both a Pre-Commit hook called `file-contents-sorter` and a test called `test_dictionary_sorting()` to enforce dictionaries have been sorted.

If I'm not missing anything, since `Pre-Commit` is enforced as a CI check before merge, the `test_dictionary_sorting()` test can be deleted. If that's accurate, I can get a PR in deleting the test.

**Comment by DimitriPapadopoulos** [comment]
Both were added in #2973. I think the explanation is in a [comment](https://github.com/codespell-project/codespell/pull/2973/files#discussion_r1276317236):
> [...] this is now enforced by the pre-commit hook, and is checked when `make check-dictionaries` is run.

Can you have a look?

**Comment by korverdev** [comment]
Truth be told, I'm not really following what they're trying to say. Are we sure they were aware that Pre-Commit is enforced as a CI check? From what I can tell, there's really no need to have both.

**Comment by DimitriPapadopoulos** [comment]
The [Makefile](https://github.com/codespell-project/codespell/blob/master/Makefile) distinguishes between **`check-dictionaries`** implemented in actual tests:
https://github.com/codespell-project/codespell/blob/edef0408c3d07d81117af5b81c7e0b926aa9caaa/Makefile#L13-L21
and **`sort-dictionaries`** implemented using pre-commit:
https://github.com/codespell-project/codespell/blob/edef0408c3d07d81117af5b81c7e0b926aa9caaa/Makefile#L27-L28
