### ISSUE TITLE
`setuptools_scm` dependency

### ISSUE THREAD

**Issue by cmelone** [codespell-project/codespell#3365]
I am packaging codespell for the [Spack package manager](https://spack.io) and I'm trying to determine what the right dependencies are. I see that there is a [constraint](https://github.com/codespell-project/codespell/blob/master/pyproject.toml#L69) on `setuptools_scm` `8.0.0` due to #3100. Does anyone know if this extends to all versions > 8, or if it's an issue specific to `8.0.0`?

@tomrijntjes

Thanks

**Comment by tomrijntjes** [comment]
Specific to 8.0.0, the issue was patched in later releases. I hope that answers your question.

**Comment by cmelone** [comment]
Yes, thank you!
