### ISSUE TITLE
Ignore regular expressions

### ISSUE THREAD

**Issue by bje-** [codespell-project/codespell#3369]
Codespell should probably ignore (by default) regular expressions. I have some new code which uses the regexp `[cC]hange` and Codespell is suggesting `hange` => `change`. It should probably be ignoring the whole word since it contains a regexp.

**Comment by DimitriPapadopoulos** [comment]
By default, we split words on **`\W`** which "[matches any character which is not a word character](https://docs.python.org/3/library/re.html#regular-expression-syntax)":
https://github.com/codespell-project/codespell/blob/6c3294016b04b594671e0e1704e096c0eec9504d/codespell_lib/_codespell.py#L31

**Comment by bje-** [comment]
Perhaps the right approach is an option to allow "words" that contain non-alphabetic characters to be ignored?

**Comment by DimitriPapadopoulos** [comment]
That's the point, there are no "words" that contain non-alphabetic characters to in your example.

**Comment by bje-** [comment]
It sounds like I'm out of luck, then?

**Comment by DimitriPapadopoulos** [comment]
To start with, you could try a different word-splitting regex that fits your use case. Detecting and interpreting a regex is a "niche" use-case for general purpose spellchecking software. Note that you would have to interpret `[^Cc]hange` too.

For constructs specific to a programming language, it might be better to parse the code yourself and pass individual words to a spellchecker.

**Comment by bje-** [comment]
Ahh, `-r` looks like it could be the workaround. Thank you.
