### ISSUE TITLE
release a new version ? 

### ISSUE THREAD

**Issue by 12rambau** [codespell-project/codespell#3387]
You recently merged https://github.com/codespell-project/codespell/pull/2400 which is adding a super cool new ignoring mechanism. Would it be possible to make a release to make it available for CI/CD that cannot rely on git repository ?

**Comment by 12rambau** [comment]
everything is living in the readme right ?

**Comment by mdeweerd** [comment]
Updated features is not the only good reason to make a release: dictionnary updates are as well.
From the tag dates I notice that there can be quite a big time lapse between releases.
Could there at least be a regular release for dictionnary updates?
Perhaps the versioning could be appended with a '-<number>' where number starts with one and is incremented for each dictionnary upgrade.  There would not be any functionnal change for a dictionnary upgrade and they would only be release for the latest code version.

**Comment by LecrisUT** [comment]
> Perhaps the versioning could be appended with a '-' where number starts with one and is incremented for each dictionnary upgrade.

I would recommend the opposite, and always have dictionary udpates on minor releases. The reasoning is that bug fixes should in general be compatible with the current version used and should not require more work to update. Dictionary updates can lead to quite a lot of work for the developers  where they might not be ready to review.

I've seen similar workflow in `cibuildwheel` where the python versions and supported OS are changed at a minor release version, particularly since it's a GH action where there is a standard to move tags. Codespell does not have moving tags/branch and pre-commit does not support that, so it is not super relevant, but still having a standard for the release would be helpful for the users.

**Comment by mdeweerd** [comment]
> > Perhaps the versioning could be appended with a '-' where number starts with one and is incremented for each dictionnary upgrade.
> 
> I would recommend the opposite, and always have dictionary updates on minor releases.

I guess that my wording was wrong because that is an intended result of my proposal - the '-1', '-2', '-3' appended to a version increment with each dictionnary update, not for functional updates.

**Comment by 12rambau** [comment]
but that's the point, changing the dictionary is a real change for users so at least a feature. I would avoid to reinvent the wheel in version naming convention to make sure that CI/CD pipeline continue to understand what is happening. 

The dash will not be interpreted thus a "<1. 2" requirement will take into consideration "1.2.1-1" and "1.2.1-2" etc which is not a wanted behaviour from my side at least.

**Comment by mdeweerd** [comment]
The "-\d+" numbering scheme was mainly an example, it can be whatever fits desires.

Another solution would be to have a package for the dictionnary that would be a dependency similar to tomli, but a required one.

The pre-commit setup provided by codespell would specify a minimum version (last one known at release time).
The user can specify another dictionnary version in the additional_dependencies section of a pre-commit configuration.
The dictionnary could use a different versioning method more indicative of how old it is (e.g., v2024.4.3).

Dictionnaries are probably compatible across versions so one could just upgrade the dictionnary without upgrading codespell itself.

**Comment by LecrisUT** [comment]
This would also work. But it should be documented that pre-commit has caveats around `additional_dependencies` [^1], which could make updating it a bit tricky. Pre-commit does cache based on [`.pre-commit-config.yaml`](https://github.com/pre-commit/action/blob/f7acafac0271bdd064cdfa1b13f17b4350e565ed/action.yml#L15-L18) so you would have to pin the dependency version there and make sure `dependabot`, [`renovate`](https://github.com/renovatebot/renovate/issues/20780) etc. update the pinned `additional_dependencies` field as well.

[^1]: https://github.com/pre-commit/pre-commit/issues/2758#issuecomment-2032471055

**Comment by edgarrmondragon** [comment]
Bump. I think this fell off yall's radar.

**Comment by DimitriPapadopoulos** [comment]
@larsoner I would like to see a new version before landing https://github.com/codespell-project/codespell/pull/3425.

**Comment by larsoner** [comment]
Just cut https://github.com/codespell-project/codespell/releases/tag/v2.3.0 / https://pypi.org/project/codespell/2.3.0/

**Comment by jamesbraza** [comment]
<img src="https://media1.giphy.com/media/LfGGW219qNzLP6IzTA/giphy.gif"/>
