### ISSUE TITLE
Are inline ignores restricted to hash-style comments?

### ISSUE THREAD

**Issue by oddhack** [codespell-project/codespell#3401]
I'd like to use them in asciidoctor markup, but the documentation suggests it is limited to

> \# codespell:ignore wrod

syntax. The closest valid asciidoctor construct that looks like an inline ignore I can think of is

> [[ # codespell:ignore wrod ]]

Is this sufficiently close to trigger the ignore feature? N.b. I do not care if it thinks it is supposed to ignore ']]', just so long as it ignores 'wrod' as well :-)

**Comment by DimitriPapadopoulos** [comment]
See #3397.
