### ISSUE TITLE
Codespell inline ignores don't appear to work in Markdown files

### ISSUE THREAD

**Issue by d33bs** [codespell-project/codespell#3429]
Hello, thanks for the great work in this project! I found that I'm running into the same as #3396 when using the latest version available via PyPI installations of Codespell. I wanted to open a new issue to help address any challenges that may be present.

My hope is to be able to use inline ignore rules through Codespell as follows:

```markdown
abandonned <!-- codespell:ignore -->
```

This doesn't appear to work with the current version deployed through PyPI.

I was able to reproduce the issue in a [Google Colab notebook](https://colab.research.google.com/drive/1dtgyEQrlsf2Q60S5aZ9BM3dwErh2nbJY), with a [Gist backup](https://gist.github.com/d33bs/5dbe75bc2798306e608c5421d2722395) (note: the gist appears to not render the markdown comment, but observe the `cat` below that cell for verification).

Please don't hesitate to let me know if you have any questions or if I may clarify at all.

**Comment by DimitriPapadopoulos** [comment]
Which version of codespell?

**Comment by DimitriPapadopoulos** [comment]
Got it. The "latest version available via PyPI" does not include #2400.

What you want is a new release. See #3387.

**Comment by d33bs** [comment]
Thanks @DimitriPapadopoulos for the clarification!
