### ISSUE TITLE
Better project description

### ISSUE THREAD

**Issue by mtelka** [codespell-project/codespell#3431]
This project deserve a bit more verbose description than [Codespell](https://github.com/codespell-project/codespell/blob/master/pyproject.toml#L5).  The reasonable project description is good for several reasons, for example it is directly visible during [PyPI search](https://pypi.org/search/?q=codespell).

**Comment by DimitriPapadopoulos** [comment]
https://github.com/codespell-project/codespell/blob/193cd7d27cd571f79358af09a8fb8997e54f8fff/pyproject.toml#L3-L5

Merge requests welcome!

**Comment by mtelka** [comment]
Is `Fix common misspellings in text files` acceptable?

**Comment by DimitriPapadopoulos** [comment]
Yes, not only acceptable, but a very good description with all the right words.
