### ISSUE TITLE
I need to ignore "image/png"  the contents of the ipynb(python) file

### ISSUE THREAD

**Issue by ruslansenatorov** [codespell-project/codespell#3436]
I need to ignore this line in the python file with the ipynb extension

![image](https://github.com/codespell-project/codespell/assets/55090151/e1eb6bd0-b3c0-4ba9-aafa-a57fbd74c40e)

**Comment by ruslansenatorov** [comment]
I insert pictures into my ipynb file, but the cat has already checked it and gives it out

**Comment by ruslansenatorov** [comment]
.pre-commit-config.yaml


 args:
          - --ignore-regex=^\s*"image\/png":\s.*


**I solved the problem, it worked**

**Comment by DimitriPapadopoulos** [comment]
Alternatives:
- Add `# codespell: ignore` at the end of the line
-  Copy the line to a file, for example `.codespell_lines_to_exclude` and run:
   ```
   codespell --exclude-file .codespell_lines_to_exclude
   ```
