### ISSUE TITLE
--ignore-words is not working in pre-commit

### ISSUE THREAD

**Issue by ZhiyuanChen** [codespell-project/codespell#3452]
I have the following [`.codespell-whitelist.txt` file](https://github.com/DLS5-Omics/multimolecule/blob/master/.codespell-whitelist.txt) and [pre-commit config](https://github.com/DLS5-Omics/multimolecule/blob/master/.pre-commit-config.yaml)

The codespell white list works perfect in Commandline with `codespell --ignore-words=.codespell-whitelist.txt`

But the pre-commit keeps complaining `https://github.com/DLS5-Omics/multimolecule/actions/runs/9500924760/job/26185184049`

**Comment by DimitriPapadopoulos** [comment]
It works for me outside pre-commit. Perhaps the concept of **current directory** underlying the use of `--ignore-words=.codespell-whitelist.txt` is not valid in pre-commit.

**Comment by ZhiyuanChen** [comment]
> 2. Please change Ser into ser.

It helped! 

I some how thought code spell was case sensitive... Thank you !
