### ISSUE TITLE
The README creates confusion about the '--interactive' flag

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [codespell-project/codespell#3491]
&nbsp;&nbsp;&nbsp;The README say, early on, that it recommends using the `-w` flag with the `-i` flag. So I tried that immediately. That led to errors and I started wondering whether flags most go in a particular position within the command. After a while I read more of the README and discovered  that `-i` takes an argument of its own. Arguably, here we have a [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK). But there is the following problem. So far as I can see, the README does not actually explain _that_ argument or, more precisely, its different possible values.

**Comment by DimitriPapadopoulos** [comment]
From the [README](https://github.com/codespell-project/codespell/blob/master/README.rst#usage):
> Below are some simple usage examples to demonstrate how the tool works. For exhaustive usage information, please check the output of `codespell -h`.
