### ISSUE TITLE
Inline word skipping does not work - at least within SublimeText

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [codespell-project/codespell#3494]
The README gives one to believe that codespell allows one, via a comment in source-code file, to skip a codespell suggestion for a particular word (and to do so, I take it, for the _whole_ file). The README gives this example:

def wrod() # codespell:ignore wrod
    pass

Yet, when I do the following, in Sublime Text with the linter 'SublimeLinter-contrib-codespell' installed, I see this:

![image](https://github.com/user-attachments/assets/d3f945f8-6255-46ed-9dbf-fc624f11d979)

Perhaps though the problem lies with the Sublime Linter (i.e., with SublimeLinter-contrib-codespell). Or perhaps I misunderstand something.

**Comment by DimitriPapadopoulos** [comment]
Can you reproduce with codespell? I don't know how Sublime Text and Sublime Linter use codespell, and which version of it.

**Comment by DimitriPapadopoulos** [comment]
Please attach a minimal `~/scripts/sendFile/syncIn` file that reproduces the problem.

**Comment by LinuxOnTheDesktop** [comment]
Here you go.

```
#!/usr/bin/env bash
# codespell: ignore syncIn
# NAME				syncIn
```

**Comment by DimitriPapadopoulos** [comment]
There are multiple issues in the above file. Try this instead:
```
#!/usr/bin/env bash
# NAME				syncIn  # codespell:ignore syncin
```

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;Thanks. I take it that you mean the following.

1) The codespell directive ought to follow, i.e. come _after_, the text that it means to allow.
2) The argument in the ignore directive ought to be entirely in lowercase.

1 - and 2? - is per the instructions. I find both 1 and 2 counter-intuitive.

**Comment by DimitriPapadopoulos** [comment]
1 is pretty standard in linters or spellcheckers.

2. is a known issue.

**Comment by LinuxOnTheDesktop** [comment]
Re _1_: aha; I was not aware of that - because no other linter that I use within Sublime works in that way.
Re _2_: right.
