### ISSUE TITLE
.codespellrc does not support multi-line configuration

### ISSUE THREAD

**Issue by tvegas1** [codespell-project/codespell#3561]
Multi-line skip configuration seems not supported, is it possible to add support for it?

Using `.codespellrc`:
```ini
[codespell]
skip = ./my_path,\
    ./my_second_path
```

Which produces:
`options.skip=['./my_path,\\\n./my_second_path']`

Which is not understood by `GlobMatch`:
```python
class GlobMatch(object):
    def __init__(self, pattern):
        if pattern:
            # Pattern might be a list of comma-delimited strings
            self.pattern_list = ','.join(pattern).split(',')
```

**Comment by DimitriPapadopoulos** [comment]
I'm not sure that's how multiline values work. See [Supported INI File Structure](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure).

**Comment by DimitriPapadopoulos** [comment]
This works for me:
```ini
[codespell]
skip = ./my_path,
    ./my_second_path
```

**Comment by DimitriPapadopoulos** [comment]
Finally, `options.skip` is not passed to `GlobalMatch` as is:
```python
    glob_match = GlobMatch(
        flatten_clean_comma_separated_arguments(options.skip) if options.skip else []
    )
```

**Comment by tvegas1** [comment]
Thanks for clarifying, my version is too old, will update it.
