### ISSUE TITLE
What is codespell/codespell_lib/data/linux-kernel.exclude ?

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#369]
What purpose does it serve ?
https://github.com/lucasdemarchi/codespell/blob/master/codespell_lib/data/linux-kernel.exclude

**Comment by larsoner** [comment]
I assume it's the set of words to be excluded when looking at the linux kernel source

**Comment by luzpaz** [comment]
so if you tack on `.exclude` to the end of a file codespell will ignore it ?

**Comment by larsoner** [comment]
No, I mean this filename can be passed with the `-x` flag

**Comment by larsoner** [comment]
Closing, feel free to update docs if it would help
