### ISSUE TITLE
The word positon isn't triggering codespell

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#393]
Create a file with the word `positon` in it. 
Run codespell on it. 
Doesn't find the typo

Running `1.13.0.dev0`

**Comment by larsoner** [comment]
I can't replicate
```
$ echo "positon" > foo.txt
$ codespell foo.txt
foo:1: positon  ==> position
```

**Comment by peternewman** [comment]
It ought to also suggest positron! :smile:

**Comment by Gelma** [comment]
gelma@glet:/tmp$ vi aua
gelma@glet:/tmp$ codespell aua
aua:2: positon  ==> position
gelma@glet:/tmp$

Latest GIT

On Linux, you can do this, so we check the real content of the file:
gelma@glet:/tmp$ hexdump aua
0000000 700a 736f 7469 6e6f 000a
0000009

gelma@glet:/tmp$ cat aua

positon

**Comment by lurch** [comment]
Can this be closed now @luzpaz ?

**Comment by peternewman** [comment]
Thanks for the PR @lurch . The typo `positon` was in the dictionary at the time, so it needs @luzpaz to do some of the diagnostics @Gelma suggested to try and find out why it's not matching the word for them.

**Comment by skangas** [comment]
Is this still an issue?
