### ISSUE TITLE
UnicodeEncodeError when running codespell through subprocess.PIPE

### ISSUE THREAD

**Issue by ahal** [codespell-project/codespell#416]
When running codespell through subprocess with stdout=subprocess.PIPE, any unicode will result in a UnicodeEncodeError. This issue comes from [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1448951). For context we have a lint wrapper that runs several linters at once (thus why we use subprocess).

**test.py**

    import subprocess
    cmd = ['codespell', 'test.txt']

    print("no pipe")
    subprocess.call(cmd)

    print("\npipe stdout")
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    print(proc.communicate()[0])

**test.txt**

    creche

**STR**

Copy both test.py and test.txt to the same directory. Then run:

    $ python test.py

**Result**

    no pipe
    test.txt:1: creche  ==> crèche

    pipe stdout
    Traceback (most recent call last):
      File "/home/ahal/.pyenv/versions/2.7.13/bin/codespell", line 11, in <module>
        sys.exit(_script_main())
      File "/home/ahal/.pyenv/versions/2.7.13/lib/python2.7/site-packages/codespell_lib/_codespell.py", line 557, in _script_main
        return main(*sys.argv[1:])
      File "/home/ahal/.pyenv/versions/2.7.13/lib/python2.7/site-packages/codespell_lib/_codespell.py", line 642, in main
        bad_count += parse_file(filename, colors, summary)
      File "/home/ahal/.pyenv/versions/2.7.13/lib/python2.7/site-packages/codespell_lib/_codespell.py", line 532, in parse_file
        'RIGHTWORD': crightword, 'REASON': creason})
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 36: ordinal not in range(128)

I believe this is happening because subprocess.PIPE is a byte stream and the codespell linter isn't encoding the output to UTF-8 before printing.

**Comment by larsoner** [comment]
I can confirm this behavior. A possible workaround would be to use python 3. Soon major libraries will move away from Python 2 (e.g., NumPy will no longer add new features at the end of 2018).

If someone wants to take a stab at fixing this, feel free. I suspect @ahal's suggestion would work.

**Comment by sylvestre** [comment]
I would be in favor of ending the support of 2.7. 
The PR #418 is also failing because of such issue.

**Comment by buhtz** [comment]
I assume this can be closed. Not relevant anymore today. I have no problems running codespell via subprocess on python3.

**Comment by DimitriPapadopoulos** [comment]
Thank you @buhtz for coming back to us.
