### ISSUE TITLE
--ignore-words= is failing to ignore some strings

### ISSUE THREAD

**Issue by sylvestre** [codespell-project/codespell#455]
with src.cpp
```
explicit PresentationTransportBuilderConstructorIPC(PresentationParent* aParent)
CAs
```
and exclude.txt
```
CAs
optin
aParent
TE
```
The following command is failing:
```
$ codespell --ignore-words=exclude.txt src.cpp 
src.cpp:1: aParent  ==> apparent
src.cpp:2: CAs  ==> case

```

**Comment by flopp** [comment]
````
-I FILE, --ignore-words=FILE
    File that contains words which will be ignored by
    codespell. File must contain 1 word per line. Words are
    case sensitive based on how they are written in
    codespell_lib/data/dictionary.txt
````
=> you have to write your exclude words as they are spelled in `dictionary.txt`.

The default `dictionary.txt` contains `aparent` and `cas` instead of `aParent` and `CAs`...

**Comment by sylvestre** [comment]
ok, my bad.

**Comment by ClementWalter** [comment]
I don't understand the answer. 

I have created a `.codespellignore` file in which I have one single line

```
KeyPair
```

codespell returns an error of a file using `KeyPair` 

```
Error: ./.codespellignore:1: KeyPair ==> key pair
Error: ./scripts/utils.py:14: KeyPair ==> key pair
```

this is really counter intuitive. What should I do?

**Comment by DimitriPapadopoulos** [comment]
1. `KeyPair` → `keypair`: it might be counter intuitive but for now words must be entered as they appear typo dictionaries:
   https://github.com/codespell-project/codespell/blob/172596b727d8b7ba4c7f0565c67e3486ab0d104c/codespell_lib/data/dictionary_code.txt#L35
2. Where did you get the idea of a file named `.codespellignore` from?

**Comment by ClementWalter** [comment]
@DimitriPapadopoulos comes from the [codespell action doc](https://github.com/codespell-project/actions-codespell#parameter-ignore_words_file) actually

but I was wondering if it was better to put this in the `pyproject.toml`, or somewhere it could be understood by VSCode spell checker as well for instance

**Comment by DimitriPapadopoulos** [comment]
Fair enough, but you do use `-I`/`--ignore` to pass `.codespellignore` as an argument, don't you? Indeed, _codespell_ will **not** look into a file named `.codespellignore` on its own, by default.

I have no clue about the VSCode spell checker and how to pass a file to it.

**Comment by ClementWalter** [comment]
> Fair enough, but you do use `-I`/`--ignore` to pass `.codespellignore` as an argument, don't you? Indeed, _codespell_ will **not** look into a file named `.codespellignore` on its own, by default.
> 
> I have no clue about the VSCode spell checker and how to pass a file with wrong positives to ignore.

indeed, it's used with `-I` I have kept the same name as in the doc though it could be anything, at least neater from the codebase point of view as it describes why this file exists
And actually putting `keypair` in it solved my issue
