### ISSUE TITLE
document quiet levels

### ISSUE THREAD

**Issue by thorade** [codespell-project/codespell#657]
Running codespell -h gives information on some of the quiet levels, but not all. 
Is it explained somewhere how to use the quiet levels?

**Comment by larsoner** [comment]
I am not aware of a more complete description. What is it missing? Feel free to add a PR to improve the `--help` description.

**Comment by thorade** [comment]
```
  -q QUIET_LEVEL, --quiet-level=QUIET_LEVEL
                        Bitmask that allows codespell to run quietly. 0: the
                        default, in which all messages are printed. 1: disable
                        warnings about wrong encoding. 2: disable warnings
                        about binary file. 4: shut down warnings about
                        automatic fixes that were disabled in dictionary. 8:
                        don't print anything for non-automatic fixes. 16:
                        don't print fixed files.
```

After reading again, I probably just misunderstood the description. 
I was thinking that there also should be levels 5,6,7,9,10,11,12,13,14,15.
But now I think that 3=1+2, and 7=1+2+4, etc
