### ISSUE TITLE
how to add "wrong" words to dictionary?

### ISSUE THREAD

**Issue by bittorf** [codespell-project/codespell#66]
i want to add 'churchs' as a _good_ word (a shoebrand!)
to my private dictionary, but codespell always want
to correct it with churchs->churches

what is the proposed way to do this?

**Comment by thdot** [comment]
You could use the `--exclude-file` option to exclude the lines containing the _good_ word explicitly.
Not the most elegant way, I know.

**Comment by bittorf** [comment]
a more elegant solution would be a comment-statement in the line with e.g.

    codespell: churchs

**Comment by bittorf** [comment]
@lucasdemarchi that is not the way i like it:

the given example is real ("churchs") but of course i do not want
to loose real occurences of a misspelled "church". think of a large file,
where only 1 thing should be overridden...

**Comment by lucasdemarchi** [comment]
I don't like the approach of adding comments in code to tweak the behavior
of codespell. Even worse that codespell doesn't know what's a comment. I'd
prefer to tell people to either use the approaches suggested above, an
exclude file. Other option: use a "2 pass approach", excluding that word I
the first and using a dictionary with only that word in the second, but in
iterative mode. This way codespell will ask for confirmation if the word
should be changed.

**Comment by thdot** [comment]
I agree with Lucas, adding comments into the code to influence codespell isn't a sustainable way. Personally I like the idea to extend the dictionary syntax, but a word exclude file is fine for me as well.

@bittorf: if you want to ignore just one occurrence of "churchs" I think the `--exclude-file` option is a good way to achieve that.

**Comment by bittorf** [comment]
@thdot - i can work with the <tt>--exclude-file</tt> approach, but it is not elegant. having statements in the file is an old and good way to talk with a compiler. see e.g. GCC or 'shellcheck': https://github.com/koalaman/shellcheck/wiki/Directive

having extra files describing an issue feels like code duplication. what is if a line moves up or down? i have to tweak my 2nd file also...

**Comment by luzpaz** [comment]
please integrate a `codespell --ignore-words /path/to/good/dictionary.txt`

**Comment by larsoner** [comment]
Fixed by #100

**Comment by bittorf** [comment]
The L flag is not enough:
This way you *ignore* the wrong word "churchs" in the whole file.

Having a "directive" in the file, you can ignore just a single occurrence
and the knowledge about this special situation is directly at the correct place.

**Comment by discordianfish** [comment]
I agree, a directive would be great! I want to be specific about where to ignore what.

**Comment by alex-zenml** [comment]
> @bittorf use the `-L` flag. Try this: `echo "churchs, churches" | codespell -L churchs -` then try `echo "churchs, churches" | codespell -`

I'm not quite sure why this example doesn't follow the pattern:

`echo "DotA" | codespell -L DotA -`

I get an error that is seemingly inextinguishable.

**Comment by peternewman** [comment]
> I'm not quite sure why this example doesn't follow the pattern:
> 
> `echo "DotA" | codespell -L DotA -`
> 
> I get an error that is seemingly inextinguishable.

Try this:
`echo "DotA" | codespell -L dota -`

>   -L WORDS, --ignore-words-list WORDS
>                         comma separated list of words to be ignored by
>                         codespell. Words are case sensitive based on how they
>                         are written in the dictionary file

@bittorf we've also got this now:
```
  -x FILE, --exclude-file FILE
                        FILE with lines that should not be checked for errors
                        or changed
```

The issue with comment directives, is e.g. you can't do them within some Pydoc or a Doxygen block or whatever (so it can't always be the line before), and you can then never write `codespell ignore=` without it ignoring something, i.e. you can't ever write a comment about that behaviour.

**Comment by 12rambau** [comment]
just an update that since https://github.com/codespell-project/codespell/pull/2400 it's now possible to add inline ignore comments.
