### ISSUE TITLE
Discussion: Is it about time for a new release?

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#823]
@larsoner  since we don't have a solution for https://github.com/codespell-project/codespell/issues/116#issuecomment-460720205
I suggest we consider making a new release. What do you think?

**Comment by larsoner** [comment]
I don't see it as being too difficult to either (1) grab the new dict manually and use it, or (2) use `pip` to install the `master` version. So I'd rather just release every 6 months or so.
