### ISSUE TITLE
Add codespell to Homebrew

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#839]
https://docs.brew.sh/Formula-Cookbook

**Comment by luzpaz** [comment]
bump, anyone on MacOS willing to do this?

**Comment by bpfoley** [comment]
In progress. See https://github.com/Homebrew/homebrew-core/pull/43258

**Comment by bpfoley** [comment]
Homebrew/homebrew-core#43258 has been merged. This can be closed now.
