### ISSUE TITLE
"cancelled" (british) -> "canceled" (american) was added to the dictionary

### ISSUE THREAD

**Issue by TysonAndre** [codespell-project/codespell#881]
This was added in eceb4c7f86fefb3a6cc5a6ff742455f38327f01e . I don't think this is deliberate, because other british spellings such as "colour"->"color" aren't a suggested correction.

Maybe there's a way to check if british spellings are on the left hand side before merging PRs (in Travis), e.g. with a british word list with pre-existing rare words (for code) removed.

related to #103 

-----

https://www.grammarly.com/blog/canceled-vs-cancelled/

**Comment by TysonAndre** [comment]
Oh, I didn't see 877

**Comment by waldyrious** [comment]
Link for convenience: #877
